/*
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.reacon.sdk.api;

import io.reacon.sdk.ApiCallback;
import io.reacon.sdk.ApiClient;
import io.reacon.sdk.ApiException;
import io.reacon.sdk.ApiResponse;
import io.reacon.sdk.Configuration;
import io.reacon.sdk.Pair;
import io.reacon.sdk.ProgressRequestBody;
import io.reacon.sdk.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.reacon.sdk.model.ApiError;
import io.reacon.sdk.model.ApiKeyIdentity;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class IdentityApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;

    public IdentityApi() {
        this(Configuration.getDefaultApiClient());
    }

    public IdentityApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }



    /**
     * Build call for getApiKeyIdentity
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> HTTP 400 error </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> HTTP 401 error </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> HTTP 403 error </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> HTTP 429 error </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> HTTP 500 error </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Unexpected API error; SDKs also retain the raw body when a proxy returns non-JSON content. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getApiKeyIdentityCall(final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/whoami";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKey" };
        return localVarApiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getApiKeyIdentityValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return getApiKeyIdentityCall(_callback);

    }

    /**
     * Get API-key identity
     * Returns the current API key ID and team ID. This route accepts API-key authentication only.
     * @return ApiKeyIdentity
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> HTTP 400 error </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> HTTP 401 error </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> HTTP 403 error </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> HTTP 429 error </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> HTTP 500 error </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Unexpected API error; SDKs also retain the raw body when a proxy returns non-JSON content. </td><td>  -  </td></tr>
     </table>
     */
    public ApiKeyIdentity getApiKeyIdentity() throws ApiException {
        ApiResponse<ApiKeyIdentity> localVarResp = getApiKeyIdentityWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Get API-key identity
     * Returns the current API key ID and team ID. This route accepts API-key authentication only.
     * @return ApiResponse&lt;ApiKeyIdentity&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> HTTP 400 error </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> HTTP 401 error </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> HTTP 403 error </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> HTTP 429 error </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> HTTP 500 error </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Unexpected API error; SDKs also retain the raw body when a proxy returns non-JSON content. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ApiKeyIdentity> getApiKeyIdentityWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = getApiKeyIdentityValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<ApiKeyIdentity>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get API-key identity (asynchronously)
     * Returns the current API key ID and team ID. This route accepts API-key authentication only.
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> HTTP 400 error </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> HTTP 401 error </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> HTTP 403 error </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> HTTP 429 error </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> HTTP 500 error </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Unexpected API error; SDKs also retain the raw body when a proxy returns non-JSON content. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getApiKeyIdentityAsync(final ApiCallback<ApiKeyIdentity> _callback) throws ApiException {

        okhttp3.Call localVarCall = getApiKeyIdentityValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<ApiKeyIdentity>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
