/*
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.reacon.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.reacon.sdk.JSON;

/**
 * BatchVerificationError
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class BatchVerificationError {
  private transient java.util.Set<String> reaconPresentFields = new java.util.HashSet<>();

  /** Whether a wire property was supplied, including an explicit null. */
  public boolean isFieldSet(String wireName) {
    switch (wireName) {
      case SERIALIZED_NAME_CODE: return reaconPresentFields.contains(SERIALIZED_NAME_CODE) || this.code != null;
      case SERIALIZED_NAME_MESSAGE: return reaconPresentFields.contains(SERIALIZED_NAME_MESSAGE) || this.message != null;
      case SERIALIZED_NAME_REMAINING_CREDITS: return reaconPresentFields.contains(SERIALIZED_NAME_REMAINING_CREDITS) || this.remainingCredits != null;
      case SERIALIZED_NAME_UPDATED_AT: return reaconPresentFields.contains(SERIALIZED_NAME_UPDATED_AT) || this.updatedAt != null;
      default: throw new IllegalArgumentException("Unknown wire property: " + wireName);
    }
  }

  /** Omit an optional property again; required properties cannot be unset. */
  public void unsetField(String wireName) {
    if (openapiRequiredFields.contains(wireName)) throw new IllegalArgumentException("Required wire property: " + wireName);
    switch (wireName) {
      case SERIALIZED_NAME_CODE: this.code = null; break;
      case SERIALIZED_NAME_MESSAGE: this.message = null; break;
      case SERIALIZED_NAME_REMAINING_CREDITS: this.remainingCredits = null; break;
      case SERIALIZED_NAME_UPDATED_AT: this.updatedAt = null; break;
      default: throw new IllegalArgumentException("Unknown wire property: " + wireName);
    }
    reaconPresentFields.remove(wireName);
  }

  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  @javax.annotation.Nonnull
  private String code;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  @javax.annotation.Nonnull
  private String message;

  public static final String SERIALIZED_NAME_REMAINING_CREDITS = "remainingCredits";
  @SerializedName(SERIALIZED_NAME_REMAINING_CREDITS)
  @javax.annotation.Nullable
  private BigDecimal remainingCredits;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime updatedAt;

  public BatchVerificationError() {
  }

  public BatchVerificationError code(@javax.annotation.Nonnull String code) {
    this.code = code;
    this.reaconPresentFields.add(SERIALIZED_NAME_CODE);
    return this;
  }

  /**
   * Get code
   * @return code
   */
  @javax.annotation.Nonnull
  public String getCode() {
    return code;
  }

  public void setCode(@javax.annotation.Nonnull String code) {
    this.code = code;
    this.reaconPresentFields.add(SERIALIZED_NAME_CODE);
  }


  public BatchVerificationError message(@javax.annotation.Nonnull String message) {
    this.message = message;
    this.reaconPresentFields.add(SERIALIZED_NAME_MESSAGE);
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @javax.annotation.Nonnull
  public String getMessage() {
    return message;
  }

  public void setMessage(@javax.annotation.Nonnull String message) {
    this.message = message;
    this.reaconPresentFields.add(SERIALIZED_NAME_MESSAGE);
  }


  public BatchVerificationError remainingCredits(@javax.annotation.Nullable BigDecimal remainingCredits) {
    this.remainingCredits = remainingCredits;
    this.reaconPresentFields.add(SERIALIZED_NAME_REMAINING_CREDITS);
    return this;
  }

  /**
   * Get remainingCredits
   * @return remainingCredits
   */
  @javax.annotation.Nullable
  public BigDecimal getRemainingCredits() {
    return remainingCredits;
  }

  public void setRemainingCredits(@javax.annotation.Nullable BigDecimal remainingCredits) {
    this.remainingCredits = remainingCredits;
    this.reaconPresentFields.add(SERIALIZED_NAME_REMAINING_CREDITS);
  }


  public BatchVerificationError updatedAt(@javax.annotation.Nonnull OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    this.reaconPresentFields.add(SERIALIZED_NAME_UPDATED_AT);
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(@javax.annotation.Nonnull OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    this.reaconPresentFields.add(SERIALIZED_NAME_UPDATED_AT);
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the BatchVerificationError instance itself
   */
  public BatchVerificationError putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatchVerificationError batchVerificationError = (BatchVerificationError) o;
    return Objects.equals(this.code, batchVerificationError.code) &&
        Objects.equals(this.message, batchVerificationError.message) &&
        Objects.equals(this.remainingCredits, batchVerificationError.remainingCredits) &&
        Objects.equals(this.updatedAt, batchVerificationError.updatedAt)&&
        Objects.equals(this.additionalProperties, batchVerificationError.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, message, remainingCredits, updatedAt, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatchVerificationError {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    remainingCredits: ").append(toIndentedString(remainingCredits)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("code", "message", "remainingCredits", "updatedAt"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("code", "message", "updatedAt"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BatchVerificationError
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BatchVerificationError.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in BatchVerificationError is not found in the empty JSON string", BatchVerificationError.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : BatchVerificationError.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("code").toString()));
      }
      if (!jsonObj.get("message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("message").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BatchVerificationError.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BatchVerificationError' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BatchVerificationError> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BatchVerificationError.class));

       return (TypeAdapter<T>) new TypeAdapter<BatchVerificationError>() {
           @Override
           public void write(JsonWriter out, BatchVerificationError value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             if (value.code == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_CODE)) obj.add(SERIALIZED_NAME_CODE, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_CODE);
             }
             if (value.message == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_MESSAGE)) obj.add(SERIALIZED_NAME_MESSAGE, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_MESSAGE);
             }
             if (value.remainingCredits == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_REMAINING_CREDITS)) obj.add(SERIALIZED_NAME_REMAINING_CREDITS, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_REMAINING_CREDITS);
             }
             if (value.updatedAt == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_UPDATED_AT)) obj.add(SERIALIZED_NAME_UPDATED_AT, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_UPDATED_AT);
             }
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonNull()) {
                     obj.add(entry.getKey(), JsonNull.INSTANCE);
                   } else if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             boolean previousSerializeNulls = out.getSerializeNulls();
             out.setSerializeNulls(true);
             try { elementAdapter.write(out, obj); }
             finally { out.setSerializeNulls(previousSerializeNulls); }
           }

           @Override
           public BatchVerificationError read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             BatchVerificationError instance = thisAdapter.fromJsonTree(jsonObj);
             instance.reaconPresentFields.addAll(jsonObj.keySet());
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BatchVerificationError given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BatchVerificationError
   * @throws IOException if the JSON string is invalid with respect to BatchVerificationError
   */
  public static BatchVerificationError fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BatchVerificationError.class);
  }

  /**
   * Convert an instance of BatchVerificationError to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

