/*
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.reacon.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.reacon.sdk.JSON;

/**
 * CapabilityEmailFound
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class CapabilityEmailFound {
  private transient java.util.Set<String> reaconPresentFields = new java.util.HashSet<>();

  /** Whether a wire property was supplied, including an explicit null. */
  public boolean isFieldSet(String wireName) {
    switch (wireName) {
      case SERIALIZED_NAME_CONFIDENCE: return reaconPresentFields.contains(SERIALIZED_NAME_CONFIDENCE) || this.confidence != null;
      case SERIALIZED_NAME_EMAIL: return reaconPresentFields.contains(SERIALIZED_NAME_EMAIL) || this.email != null;
      case SERIALIZED_NAME_FRESHNESS: return reaconPresentFields.contains(SERIALIZED_NAME_FRESHNESS) || this.freshness != null;
      case SERIALIZED_NAME_STATUS: return reaconPresentFields.contains(SERIALIZED_NAME_STATUS) || this.status != null;
      default: throw new IllegalArgumentException("Unknown wire property: " + wireName);
    }
  }

  /** Omit an optional property again; required properties cannot be unset. */
  public void unsetField(String wireName) {
    if (openapiRequiredFields.contains(wireName)) throw new IllegalArgumentException("Required wire property: " + wireName);
    switch (wireName) {
      case SERIALIZED_NAME_CONFIDENCE: this.confidence = null; break;
      case SERIALIZED_NAME_EMAIL: this.email = null; break;
      case SERIALIZED_NAME_FRESHNESS: this.freshness = null; break;
      case SERIALIZED_NAME_STATUS: this.status = null; break;
      default: throw new IllegalArgumentException("Unknown wire property: " + wireName);
    }
    reaconPresentFields.remove(wireName);
  }

  public static final String SERIALIZED_NAME_CONFIDENCE = "confidence";
  @SerializedName(SERIALIZED_NAME_CONFIDENCE)
  @javax.annotation.Nonnull
  private BigDecimal confidence;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  @javax.annotation.Nonnull
  private String email;

  public static final String SERIALIZED_NAME_FRESHNESS = "freshness";
  @SerializedName(SERIALIZED_NAME_FRESHNESS)
  @javax.annotation.Nonnull
  private String freshness;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nonnull
  private String status;

  public CapabilityEmailFound() {
  }

  public CapabilityEmailFound confidence(@javax.annotation.Nonnull BigDecimal confidence) {
    this.confidence = confidence;
    this.reaconPresentFields.add(SERIALIZED_NAME_CONFIDENCE);
    return this;
  }

  /**
   * Get confidence
   * @return confidence
   */
  @javax.annotation.Nonnull
  public BigDecimal getConfidence() {
    return confidence;
  }

  public void setConfidence(@javax.annotation.Nonnull BigDecimal confidence) {
    this.confidence = confidence;
    this.reaconPresentFields.add(SERIALIZED_NAME_CONFIDENCE);
  }


  public CapabilityEmailFound email(@javax.annotation.Nonnull String email) {
    this.email = email;
    this.reaconPresentFields.add(SERIALIZED_NAME_EMAIL);
    return this;
  }

  /**
   * Get email
   * @return email
   */
  @javax.annotation.Nonnull
  public String getEmail() {
    return email;
  }

  public void setEmail(@javax.annotation.Nonnull String email) {
    this.email = email;
    this.reaconPresentFields.add(SERIALIZED_NAME_EMAIL);
  }


  public CapabilityEmailFound freshness(@javax.annotation.Nonnull String freshness) {
    this.freshness = freshness;
    this.reaconPresentFields.add(SERIALIZED_NAME_FRESHNESS);
    return this;
  }

  /**
   * Get freshness
   * @return freshness
   */
  @javax.annotation.Nonnull
  public String getFreshness() {
    return freshness;
  }

  public void setFreshness(@javax.annotation.Nonnull String freshness) {
    this.freshness = freshness;
    this.reaconPresentFields.add(SERIALIZED_NAME_FRESHNESS);
  }


  public CapabilityEmailFound status(@javax.annotation.Nonnull String status) {
    this.status = status;
    this.reaconPresentFields.add(SERIALIZED_NAME_STATUS);
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  public String getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nonnull String status) {
    this.status = status;
    this.reaconPresentFields.add(SERIALIZED_NAME_STATUS);
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the CapabilityEmailFound instance itself
   */
  public CapabilityEmailFound putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CapabilityEmailFound capabilityEmailFound = (CapabilityEmailFound) o;
    return Objects.equals(this.confidence, capabilityEmailFound.confidence) &&
        Objects.equals(this.email, capabilityEmailFound.email) &&
        Objects.equals(this.freshness, capabilityEmailFound.freshness) &&
        Objects.equals(this.status, capabilityEmailFound.status)&&
        Objects.equals(this.additionalProperties, capabilityEmailFound.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(confidence, email, freshness, status, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CapabilityEmailFound {\n");
    sb.append("    confidence: ").append(toIndentedString(confidence)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    freshness: ").append(toIndentedString(freshness)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("confidence", "email", "freshness", "status"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("confidence", "email", "freshness", "status"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CapabilityEmailFound
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CapabilityEmailFound.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in CapabilityEmailFound is not found in the empty JSON string", CapabilityEmailFound.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CapabilityEmailFound.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("email").toString()));
      }
      if (!jsonObj.get("freshness").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `freshness` to be a primitive type in the JSON string but got `%s`", jsonObj.get("freshness").toString()));
      }
      if (!jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CapabilityEmailFound.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CapabilityEmailFound' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CapabilityEmailFound> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CapabilityEmailFound.class));

       return (TypeAdapter<T>) new TypeAdapter<CapabilityEmailFound>() {
           @Override
           public void write(JsonWriter out, CapabilityEmailFound value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             if (value.confidence == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_CONFIDENCE)) obj.add(SERIALIZED_NAME_CONFIDENCE, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_CONFIDENCE);
             }
             if (value.email == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_EMAIL)) obj.add(SERIALIZED_NAME_EMAIL, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_EMAIL);
             }
             if (value.freshness == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_FRESHNESS)) obj.add(SERIALIZED_NAME_FRESHNESS, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_FRESHNESS);
             }
             if (value.status == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_STATUS)) obj.add(SERIALIZED_NAME_STATUS, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_STATUS);
             }
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonNull()) {
                     obj.add(entry.getKey(), JsonNull.INSTANCE);
                   } else if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             boolean previousSerializeNulls = out.getSerializeNulls();
             out.setSerializeNulls(true);
             try { elementAdapter.write(out, obj); }
             finally { out.setSerializeNulls(previousSerializeNulls); }
           }

           @Override
           public CapabilityEmailFound read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             CapabilityEmailFound instance = thisAdapter.fromJsonTree(jsonObj);
             instance.reaconPresentFields.addAll(jsonObj.keySet());
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CapabilityEmailFound given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CapabilityEmailFound
   * @throws IOException if the JSON string is invalid with respect to CapabilityEmailFound
   */
  public static CapabilityEmailFound fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CapabilityEmailFound.class);
  }

  /**
   * Convert an instance of CapabilityEmailFound to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

