/*
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.reacon.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.reacon.sdk.JSON;

/**
 * CompanyListResultsInnerAddressesInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class CompanyListResultsInnerAddressesInner {
  private transient java.util.Set<String> reaconPresentFields = new java.util.HashSet<>();

  /** Whether a wire property was supplied, including an explicit null. */
  public boolean isFieldSet(String wireName) {
    switch (wireName) {
      case SERIALIZED_NAME_ADDRESS_COUNTRY: return reaconPresentFields.contains(SERIALIZED_NAME_ADDRESS_COUNTRY) || this.addressCountry != null;
      case SERIALIZED_NAME_ADDRESS_LOCALITY: return reaconPresentFields.contains(SERIALIZED_NAME_ADDRESS_LOCALITY) || this.addressLocality != null;
      case SERIALIZED_NAME_ADDRESS_REGION: return reaconPresentFields.contains(SERIALIZED_NAME_ADDRESS_REGION) || this.addressRegion != null;
      case SERIALIZED_NAME_POSTAL_CODE: return reaconPresentFields.contains(SERIALIZED_NAME_POSTAL_CODE) || this.postalCode != null;
      case SERIALIZED_NAME_STREET_ADDRESS: return reaconPresentFields.contains(SERIALIZED_NAME_STREET_ADDRESS) || this.streetAddress != null;
      case SERIALIZED_NAME_TYPE: return reaconPresentFields.contains(SERIALIZED_NAME_TYPE) || this.type != null;
      default: throw new IllegalArgumentException("Unknown wire property: " + wireName);
    }
  }

  /** Omit an optional property again; required properties cannot be unset. */
  public void unsetField(String wireName) {
    if (openapiRequiredFields.contains(wireName)) throw new IllegalArgumentException("Required wire property: " + wireName);
    switch (wireName) {
      case SERIALIZED_NAME_ADDRESS_COUNTRY: this.addressCountry = null; break;
      case SERIALIZED_NAME_ADDRESS_LOCALITY: this.addressLocality = null; break;
      case SERIALIZED_NAME_ADDRESS_REGION: this.addressRegion = null; break;
      case SERIALIZED_NAME_POSTAL_CODE: this.postalCode = null; break;
      case SERIALIZED_NAME_STREET_ADDRESS: this.streetAddress = null; break;
      case SERIALIZED_NAME_TYPE: this.type = null; break;
      default: throw new IllegalArgumentException("Unknown wire property: " + wireName);
    }
    reaconPresentFields.remove(wireName);
  }

  public static final String SERIALIZED_NAME_ADDRESS_COUNTRY = "addressCountry";
  @SerializedName(SERIALIZED_NAME_ADDRESS_COUNTRY)
  @javax.annotation.Nullable
  private String addressCountry;

  public static final String SERIALIZED_NAME_ADDRESS_LOCALITY = "addressLocality";
  @SerializedName(SERIALIZED_NAME_ADDRESS_LOCALITY)
  @javax.annotation.Nullable
  private String addressLocality;

  public static final String SERIALIZED_NAME_ADDRESS_REGION = "addressRegion";
  @SerializedName(SERIALIZED_NAME_ADDRESS_REGION)
  @javax.annotation.Nullable
  private String addressRegion;

  public static final String SERIALIZED_NAME_POSTAL_CODE = "postalCode";
  @SerializedName(SERIALIZED_NAME_POSTAL_CODE)
  @javax.annotation.Nullable
  private String postalCode;

  public static final String SERIALIZED_NAME_STREET_ADDRESS = "streetAddress";
  @SerializedName(SERIALIZED_NAME_STREET_ADDRESS)
  @javax.annotation.Nullable
  private String streetAddress;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nullable
  private String type;

  public CompanyListResultsInnerAddressesInner() {
  }

  public CompanyListResultsInnerAddressesInner addressCountry(@javax.annotation.Nullable String addressCountry) {
    this.addressCountry = addressCountry;
    this.reaconPresentFields.add(SERIALIZED_NAME_ADDRESS_COUNTRY);
    return this;
  }

  /**
   * Get addressCountry
   * @return addressCountry
   */
  @javax.annotation.Nullable
  public String getAddressCountry() {
    return addressCountry;
  }

  public void setAddressCountry(@javax.annotation.Nullable String addressCountry) {
    this.addressCountry = addressCountry;
    this.reaconPresentFields.add(SERIALIZED_NAME_ADDRESS_COUNTRY);
  }


  public CompanyListResultsInnerAddressesInner addressLocality(@javax.annotation.Nullable String addressLocality) {
    this.addressLocality = addressLocality;
    this.reaconPresentFields.add(SERIALIZED_NAME_ADDRESS_LOCALITY);
    return this;
  }

  /**
   * Get addressLocality
   * @return addressLocality
   */
  @javax.annotation.Nullable
  public String getAddressLocality() {
    return addressLocality;
  }

  public void setAddressLocality(@javax.annotation.Nullable String addressLocality) {
    this.addressLocality = addressLocality;
    this.reaconPresentFields.add(SERIALIZED_NAME_ADDRESS_LOCALITY);
  }


  public CompanyListResultsInnerAddressesInner addressRegion(@javax.annotation.Nullable String addressRegion) {
    this.addressRegion = addressRegion;
    this.reaconPresentFields.add(SERIALIZED_NAME_ADDRESS_REGION);
    return this;
  }

  /**
   * Get addressRegion
   * @return addressRegion
   */
  @javax.annotation.Nullable
  public String getAddressRegion() {
    return addressRegion;
  }

  public void setAddressRegion(@javax.annotation.Nullable String addressRegion) {
    this.addressRegion = addressRegion;
    this.reaconPresentFields.add(SERIALIZED_NAME_ADDRESS_REGION);
  }


  public CompanyListResultsInnerAddressesInner postalCode(@javax.annotation.Nullable String postalCode) {
    this.postalCode = postalCode;
    this.reaconPresentFields.add(SERIALIZED_NAME_POSTAL_CODE);
    return this;
  }

  /**
   * Get postalCode
   * @return postalCode
   */
  @javax.annotation.Nullable
  public String getPostalCode() {
    return postalCode;
  }

  public void setPostalCode(@javax.annotation.Nullable String postalCode) {
    this.postalCode = postalCode;
    this.reaconPresentFields.add(SERIALIZED_NAME_POSTAL_CODE);
  }


  public CompanyListResultsInnerAddressesInner streetAddress(@javax.annotation.Nullable String streetAddress) {
    this.streetAddress = streetAddress;
    this.reaconPresentFields.add(SERIALIZED_NAME_STREET_ADDRESS);
    return this;
  }

  /**
   * Get streetAddress
   * @return streetAddress
   */
  @javax.annotation.Nullable
  public String getStreetAddress() {
    return streetAddress;
  }

  public void setStreetAddress(@javax.annotation.Nullable String streetAddress) {
    this.streetAddress = streetAddress;
    this.reaconPresentFields.add(SERIALIZED_NAME_STREET_ADDRESS);
  }


  public CompanyListResultsInnerAddressesInner type(@javax.annotation.Nullable String type) {
    this.type = type;
    this.reaconPresentFields.add(SERIALIZED_NAME_TYPE);
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nullable
  public String getType() {
    return type;
  }

  public void setType(@javax.annotation.Nullable String type) {
    this.type = type;
    this.reaconPresentFields.add(SERIALIZED_NAME_TYPE);
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompanyListResultsInnerAddressesInner companyListResultsInnerAddressesInner = (CompanyListResultsInnerAddressesInner) o;
    return Objects.equals(this.addressCountry, companyListResultsInnerAddressesInner.addressCountry) &&
        Objects.equals(this.addressLocality, companyListResultsInnerAddressesInner.addressLocality) &&
        Objects.equals(this.addressRegion, companyListResultsInnerAddressesInner.addressRegion) &&
        Objects.equals(this.postalCode, companyListResultsInnerAddressesInner.postalCode) &&
        Objects.equals(this.streetAddress, companyListResultsInnerAddressesInner.streetAddress) &&
        Objects.equals(this.type, companyListResultsInnerAddressesInner.type);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(addressCountry, addressLocality, addressRegion, postalCode, streetAddress, type);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompanyListResultsInnerAddressesInner {\n");
    sb.append("    addressCountry: ").append(toIndentedString(addressCountry)).append("\n");
    sb.append("    addressLocality: ").append(toIndentedString(addressLocality)).append("\n");
    sb.append("    addressRegion: ").append(toIndentedString(addressRegion)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    streetAddress: ").append(toIndentedString(streetAddress)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("addressCountry", "addressLocality", "addressRegion", "postalCode", "streetAddress", "type"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CompanyListResultsInnerAddressesInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CompanyListResultsInnerAddressesInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in CompanyListResultsInnerAddressesInner is not found in the empty JSON string", CompanyListResultsInnerAddressesInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CompanyListResultsInnerAddressesInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `CompanyListResultsInnerAddressesInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("addressCountry") != null && !jsonObj.get("addressCountry").isJsonNull()) && !jsonObj.get("addressCountry").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `addressCountry` to be a primitive type in the JSON string but got `%s`", jsonObj.get("addressCountry").toString()));
      }
      if ((jsonObj.get("addressLocality") != null && !jsonObj.get("addressLocality").isJsonNull()) && !jsonObj.get("addressLocality").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `addressLocality` to be a primitive type in the JSON string but got `%s`", jsonObj.get("addressLocality").toString()));
      }
      if ((jsonObj.get("addressRegion") != null && !jsonObj.get("addressRegion").isJsonNull()) && !jsonObj.get("addressRegion").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `addressRegion` to be a primitive type in the JSON string but got `%s`", jsonObj.get("addressRegion").toString()));
      }
      if ((jsonObj.get("postalCode") != null && !jsonObj.get("postalCode").isJsonNull()) && !jsonObj.get("postalCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `postalCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("postalCode").toString()));
      }
      if ((jsonObj.get("streetAddress") != null && !jsonObj.get("streetAddress").isJsonNull()) && !jsonObj.get("streetAddress").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `streetAddress` to be a primitive type in the JSON string but got `%s`", jsonObj.get("streetAddress").toString()));
      }
      if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) && !jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CompanyListResultsInnerAddressesInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CompanyListResultsInnerAddressesInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CompanyListResultsInnerAddressesInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CompanyListResultsInnerAddressesInner.class));

       return (TypeAdapter<T>) new TypeAdapter<CompanyListResultsInnerAddressesInner>() {
           @Override
           public void write(JsonWriter out, CompanyListResultsInnerAddressesInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             if (value.addressCountry == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_ADDRESS_COUNTRY)) obj.add(SERIALIZED_NAME_ADDRESS_COUNTRY, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_ADDRESS_COUNTRY);
             }
             if (value.addressLocality == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_ADDRESS_LOCALITY)) obj.add(SERIALIZED_NAME_ADDRESS_LOCALITY, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_ADDRESS_LOCALITY);
             }
             if (value.addressRegion == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_ADDRESS_REGION)) obj.add(SERIALIZED_NAME_ADDRESS_REGION, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_ADDRESS_REGION);
             }
             if (value.postalCode == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_POSTAL_CODE)) obj.add(SERIALIZED_NAME_POSTAL_CODE, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_POSTAL_CODE);
             }
             if (value.streetAddress == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_STREET_ADDRESS)) obj.add(SERIALIZED_NAME_STREET_ADDRESS, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_STREET_ADDRESS);
             }
             if (value.type == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_TYPE)) obj.add(SERIALIZED_NAME_TYPE, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_TYPE);
             }
             boolean previousSerializeNulls = out.getSerializeNulls();
             out.setSerializeNulls(true);
             try { elementAdapter.write(out, obj); }
             finally { out.setSerializeNulls(previousSerializeNulls); }
           }

           @Override
           public CompanyListResultsInnerAddressesInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             CompanyListResultsInnerAddressesInner instance = thisAdapter.fromJsonTree(jsonElement);
             instance.reaconPresentFields.addAll(jsonElement.getAsJsonObject().keySet());
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CompanyListResultsInnerAddressesInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CompanyListResultsInnerAddressesInner
   * @throws IOException if the JSON string is invalid with respect to CompanyListResultsInnerAddressesInner
   */
  public static CompanyListResultsInnerAddressesInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CompanyListResultsInnerAddressesInner.class);
  }

  /**
   * Convert an instance of CompanyListResultsInnerAddressesInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

