/*
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.reacon.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.Set;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.reacon.sdk.JSON;

/**
 * ConfigureCrmSyncRequestConfigurationPolicy
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class ConfigureCrmSyncRequestConfigurationPolicy {
  private transient java.util.Set<String> reaconPresentFields = new java.util.HashSet<>();

  /** Whether a wire property was supplied, including an explicit null. */
  public boolean isFieldSet(String wireName) {
    switch (wireName) {
      case SERIALIZED_NAME_CREATE_ON: return reaconPresentFields.contains(SERIALIZED_NAME_CREATE_ON) || this.createOn != null;
      case SERIALIZED_NAME_DELETE_ON_LEAD_DELETED: return reaconPresentFields.contains(SERIALIZED_NAME_DELETE_ON_LEAD_DELETED) || this.deleteOnLeadDeleted != null;
      case SERIALIZED_NAME_LOG_ACTIVITY: return reaconPresentFields.contains(SERIALIZED_NAME_LOG_ACTIVITY) || this.logActivity != null;
      case SERIALIZED_NAME_UPDATE_ON_LEAD_UPDATED: return reaconPresentFields.contains(SERIALIZED_NAME_UPDATE_ON_LEAD_UPDATED) || this.updateOnLeadUpdated != null;
      default: throw new IllegalArgumentException("Unknown wire property: " + wireName);
    }
  }

  /** Omit an optional property again; required properties cannot be unset. */
  public void unsetField(String wireName) {
    if (openapiRequiredFields.contains(wireName)) throw new IllegalArgumentException("Required wire property: " + wireName);
    switch (wireName) {
      case SERIALIZED_NAME_CREATE_ON: this.createOn = null; break;
      case SERIALIZED_NAME_DELETE_ON_LEAD_DELETED: this.deleteOnLeadDeleted = null; break;
      case SERIALIZED_NAME_LOG_ACTIVITY: this.logActivity = null; break;
      case SERIALIZED_NAME_UPDATE_ON_LEAD_UPDATED: this.updateOnLeadUpdated = null; break;
      default: throw new IllegalArgumentException("Unknown wire property: " + wireName);
    }
    reaconPresentFields.remove(wireName);
  }

  /**
   * Gets or Sets createOn
   */
  @JsonAdapter(CreateOnEnum.Adapter.class)
  public enum CreateOnEnum {
    LEAD_CREATED("lead.created"),
    
    SEQUENCE_EMAIL_SENT("sequence.email.sent");

    private String value;

    CreateOnEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CreateOnEnum fromValue(String value) {
      for (CreateOnEnum b : CreateOnEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<CreateOnEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CreateOnEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CreateOnEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return CreateOnEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      CreateOnEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_CREATE_ON = "createOn";
  @SerializedName(SERIALIZED_NAME_CREATE_ON)
  @javax.annotation.Nonnull
  private Set<CreateOnEnum> createOn = new LinkedHashSet<>();

  public static final String SERIALIZED_NAME_DELETE_ON_LEAD_DELETED = "deleteOnLeadDeleted";
  @SerializedName(SERIALIZED_NAME_DELETE_ON_LEAD_DELETED)
  @javax.annotation.Nonnull
  private Boolean deleteOnLeadDeleted;

  public static final String SERIALIZED_NAME_LOG_ACTIVITY = "logActivity";
  @SerializedName(SERIALIZED_NAME_LOG_ACTIVITY)
  @javax.annotation.Nonnull
  private Boolean logActivity;

  public static final String SERIALIZED_NAME_UPDATE_ON_LEAD_UPDATED = "updateOnLeadUpdated";
  @SerializedName(SERIALIZED_NAME_UPDATE_ON_LEAD_UPDATED)
  @javax.annotation.Nonnull
  private Boolean updateOnLeadUpdated;

  public ConfigureCrmSyncRequestConfigurationPolicy() {
  }

  public ConfigureCrmSyncRequestConfigurationPolicy createOn(@javax.annotation.Nonnull Set<CreateOnEnum> createOn) {
    this.createOn = createOn;
    this.reaconPresentFields.add(SERIALIZED_NAME_CREATE_ON);
    return this;
  }

  public ConfigureCrmSyncRequestConfigurationPolicy addCreateOnItem(CreateOnEnum createOnItem) {
    if (this.createOn == null) {
      this.createOn = new LinkedHashSet<>();
    }
    this.createOn.add(createOnItem);
    return this;
  }

  /**
   * Get createOn
   * @return createOn
   */
  @javax.annotation.Nonnull
  public Set<CreateOnEnum> getCreateOn() {
    return createOn;
  }

  public void setCreateOn(@javax.annotation.Nonnull Set<CreateOnEnum> createOn) {
    this.createOn = createOn;
    this.reaconPresentFields.add(SERIALIZED_NAME_CREATE_ON);
  }


  public ConfigureCrmSyncRequestConfigurationPolicy deleteOnLeadDeleted(@javax.annotation.Nonnull Boolean deleteOnLeadDeleted) {
    this.deleteOnLeadDeleted = deleteOnLeadDeleted;
    this.reaconPresentFields.add(SERIALIZED_NAME_DELETE_ON_LEAD_DELETED);
    return this;
  }

  /**
   * Get deleteOnLeadDeleted
   * @return deleteOnLeadDeleted
   */
  @javax.annotation.Nonnull
  public Boolean getDeleteOnLeadDeleted() {
    return deleteOnLeadDeleted;
  }

  public void setDeleteOnLeadDeleted(@javax.annotation.Nonnull Boolean deleteOnLeadDeleted) {
    this.deleteOnLeadDeleted = deleteOnLeadDeleted;
    this.reaconPresentFields.add(SERIALIZED_NAME_DELETE_ON_LEAD_DELETED);
  }


  public ConfigureCrmSyncRequestConfigurationPolicy logActivity(@javax.annotation.Nonnull Boolean logActivity) {
    this.logActivity = logActivity;
    this.reaconPresentFields.add(SERIALIZED_NAME_LOG_ACTIVITY);
    return this;
  }

  /**
   * Get logActivity
   * @return logActivity
   */
  @javax.annotation.Nonnull
  public Boolean getLogActivity() {
    return logActivity;
  }

  public void setLogActivity(@javax.annotation.Nonnull Boolean logActivity) {
    this.logActivity = logActivity;
    this.reaconPresentFields.add(SERIALIZED_NAME_LOG_ACTIVITY);
  }


  public ConfigureCrmSyncRequestConfigurationPolicy updateOnLeadUpdated(@javax.annotation.Nonnull Boolean updateOnLeadUpdated) {
    this.updateOnLeadUpdated = updateOnLeadUpdated;
    this.reaconPresentFields.add(SERIALIZED_NAME_UPDATE_ON_LEAD_UPDATED);
    return this;
  }

  /**
   * Get updateOnLeadUpdated
   * @return updateOnLeadUpdated
   */
  @javax.annotation.Nonnull
  public Boolean getUpdateOnLeadUpdated() {
    return updateOnLeadUpdated;
  }

  public void setUpdateOnLeadUpdated(@javax.annotation.Nonnull Boolean updateOnLeadUpdated) {
    this.updateOnLeadUpdated = updateOnLeadUpdated;
    this.reaconPresentFields.add(SERIALIZED_NAME_UPDATE_ON_LEAD_UPDATED);
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigureCrmSyncRequestConfigurationPolicy configureCrmSyncRequestConfigurationPolicy = (ConfigureCrmSyncRequestConfigurationPolicy) o;
    return Objects.equals(this.createOn, configureCrmSyncRequestConfigurationPolicy.createOn) &&
        Objects.equals(this.deleteOnLeadDeleted, configureCrmSyncRequestConfigurationPolicy.deleteOnLeadDeleted) &&
        Objects.equals(this.logActivity, configureCrmSyncRequestConfigurationPolicy.logActivity) &&
        Objects.equals(this.updateOnLeadUpdated, configureCrmSyncRequestConfigurationPolicy.updateOnLeadUpdated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createOn, deleteOnLeadDeleted, logActivity, updateOnLeadUpdated);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigureCrmSyncRequestConfigurationPolicy {\n");
    sb.append("    createOn: ").append(toIndentedString(createOn)).append("\n");
    sb.append("    deleteOnLeadDeleted: ").append(toIndentedString(deleteOnLeadDeleted)).append("\n");
    sb.append("    logActivity: ").append(toIndentedString(logActivity)).append("\n");
    sb.append("    updateOnLeadUpdated: ").append(toIndentedString(updateOnLeadUpdated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("createOn", "deleteOnLeadDeleted", "logActivity", "updateOnLeadUpdated"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("createOn", "deleteOnLeadDeleted", "logActivity", "updateOnLeadUpdated"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ConfigureCrmSyncRequestConfigurationPolicy
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ConfigureCrmSyncRequestConfigurationPolicy.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ConfigureCrmSyncRequestConfigurationPolicy is not found in the empty JSON string", ConfigureCrmSyncRequestConfigurationPolicy.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ConfigureCrmSyncRequestConfigurationPolicy.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ConfigureCrmSyncRequestConfigurationPolicy` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ConfigureCrmSyncRequestConfigurationPolicy.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the required json array is present
      if (jsonObj.get("createOn") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("createOn").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `createOn` to be an array in the JSON string but got `%s`", jsonObj.get("createOn").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ConfigureCrmSyncRequestConfigurationPolicy.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ConfigureCrmSyncRequestConfigurationPolicy' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ConfigureCrmSyncRequestConfigurationPolicy> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ConfigureCrmSyncRequestConfigurationPolicy.class));

       return (TypeAdapter<T>) new TypeAdapter<ConfigureCrmSyncRequestConfigurationPolicy>() {
           @Override
           public void write(JsonWriter out, ConfigureCrmSyncRequestConfigurationPolicy value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             if (value.createOn == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_CREATE_ON)) obj.add(SERIALIZED_NAME_CREATE_ON, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_CREATE_ON);
             }
             if (value.deleteOnLeadDeleted == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_DELETE_ON_LEAD_DELETED)) obj.add(SERIALIZED_NAME_DELETE_ON_LEAD_DELETED, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_DELETE_ON_LEAD_DELETED);
             }
             if (value.logActivity == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_LOG_ACTIVITY)) obj.add(SERIALIZED_NAME_LOG_ACTIVITY, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_LOG_ACTIVITY);
             }
             if (value.updateOnLeadUpdated == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_UPDATE_ON_LEAD_UPDATED)) obj.add(SERIALIZED_NAME_UPDATE_ON_LEAD_UPDATED, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_UPDATE_ON_LEAD_UPDATED);
             }
             boolean previousSerializeNulls = out.getSerializeNulls();
             out.setSerializeNulls(true);
             try { elementAdapter.write(out, obj); }
             finally { out.setSerializeNulls(previousSerializeNulls); }
           }

           @Override
           public ConfigureCrmSyncRequestConfigurationPolicy read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             ConfigureCrmSyncRequestConfigurationPolicy instance = thisAdapter.fromJsonTree(jsonElement);
             instance.reaconPresentFields.addAll(jsonElement.getAsJsonObject().keySet());
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ConfigureCrmSyncRequestConfigurationPolicy given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ConfigureCrmSyncRequestConfigurationPolicy
   * @throws IOException if the JSON string is invalid with respect to ConfigureCrmSyncRequestConfigurationPolicy
   */
  public static ConfigureCrmSyncRequestConfigurationPolicy fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ConfigureCrmSyncRequestConfigurationPolicy.class);
  }

  /**
   * Convert an instance of ConfigureCrmSyncRequestConfigurationPolicy to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

