/*
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.reacon.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.reacon.sdk.JSON;

/**
 * CrmRemoteField
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class CrmRemoteField {
  private transient java.util.Set<String> reaconPresentFields = new java.util.HashSet<>();

  /** Whether a wire property was supplied, including an explicit null. */
  public boolean isFieldSet(String wireName) {
    switch (wireName) {
      case SERIALIZED_NAME_DATA_TYPE: return reaconPresentFields.contains(SERIALIZED_NAME_DATA_TYPE) || this.dataType != null;
      case SERIALIZED_NAME_EXTERNAL_ID: return reaconPresentFields.contains(SERIALIZED_NAME_EXTERNAL_ID) || this.externalId != null;
      case SERIALIZED_NAME_KEY: return reaconPresentFields.contains(SERIALIZED_NAME_KEY) || this.key != null;
      case SERIALIZED_NAME_LABEL: return reaconPresentFields.contains(SERIALIZED_NAME_LABEL) || this.label != null;
      case SERIALIZED_NAME_REQUIRED: return reaconPresentFields.contains(SERIALIZED_NAME_REQUIRED) || this.required != null;
      case SERIALIZED_NAME_UNIQUE: return reaconPresentFields.contains(SERIALIZED_NAME_UNIQUE) || this.unique != null;
      default: throw new IllegalArgumentException("Unknown wire property: " + wireName);
    }
  }

  /** Omit an optional property again; required properties cannot be unset. */
  public void unsetField(String wireName) {
    if (openapiRequiredFields.contains(wireName)) throw new IllegalArgumentException("Required wire property: " + wireName);
    switch (wireName) {
      case SERIALIZED_NAME_DATA_TYPE: this.dataType = null; break;
      case SERIALIZED_NAME_EXTERNAL_ID: this.externalId = null; break;
      case SERIALIZED_NAME_KEY: this.key = null; break;
      case SERIALIZED_NAME_LABEL: this.label = null; break;
      case SERIALIZED_NAME_REQUIRED: this.required = null; break;
      case SERIALIZED_NAME_UNIQUE: this.unique = null; break;
      default: throw new IllegalArgumentException("Unknown wire property: " + wireName);
    }
    reaconPresentFields.remove(wireName);
  }

  public static final String SERIALIZED_NAME_DATA_TYPE = "dataType";
  @SerializedName(SERIALIZED_NAME_DATA_TYPE)
  @javax.annotation.Nonnull
  private String dataType;

  public static final String SERIALIZED_NAME_EXTERNAL_ID = "externalId";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_ID)
  @javax.annotation.Nonnull
  private Boolean externalId;

  public static final String SERIALIZED_NAME_KEY = "key";
  @SerializedName(SERIALIZED_NAME_KEY)
  @javax.annotation.Nonnull
  private String key;

  public static final String SERIALIZED_NAME_LABEL = "label";
  @SerializedName(SERIALIZED_NAME_LABEL)
  @javax.annotation.Nonnull
  private String label;

  public static final String SERIALIZED_NAME_REQUIRED = "required";
  @SerializedName(SERIALIZED_NAME_REQUIRED)
  @javax.annotation.Nonnull
  private Boolean required;

  public static final String SERIALIZED_NAME_UNIQUE = "unique";
  @SerializedName(SERIALIZED_NAME_UNIQUE)
  @javax.annotation.Nonnull
  private Boolean unique;

  public CrmRemoteField() {
  }

  public CrmRemoteField dataType(@javax.annotation.Nonnull String dataType) {
    this.dataType = dataType;
    this.reaconPresentFields.add(SERIALIZED_NAME_DATA_TYPE);
    return this;
  }

  /**
   * Get dataType
   * @return dataType
   */
  @javax.annotation.Nonnull
  public String getDataType() {
    return dataType;
  }

  public void setDataType(@javax.annotation.Nonnull String dataType) {
    this.dataType = dataType;
    this.reaconPresentFields.add(SERIALIZED_NAME_DATA_TYPE);
  }


  public CrmRemoteField externalId(@javax.annotation.Nonnull Boolean externalId) {
    this.externalId = externalId;
    this.reaconPresentFields.add(SERIALIZED_NAME_EXTERNAL_ID);
    return this;
  }

  /**
   * Get externalId
   * @return externalId
   */
  @javax.annotation.Nonnull
  public Boolean getExternalId() {
    return externalId;
  }

  public void setExternalId(@javax.annotation.Nonnull Boolean externalId) {
    this.externalId = externalId;
    this.reaconPresentFields.add(SERIALIZED_NAME_EXTERNAL_ID);
  }


  public CrmRemoteField key(@javax.annotation.Nonnull String key) {
    this.key = key;
    this.reaconPresentFields.add(SERIALIZED_NAME_KEY);
    return this;
  }

  /**
   * Get key
   * @return key
   */
  @javax.annotation.Nonnull
  public String getKey() {
    return key;
  }

  public void setKey(@javax.annotation.Nonnull String key) {
    this.key = key;
    this.reaconPresentFields.add(SERIALIZED_NAME_KEY);
  }


  public CrmRemoteField label(@javax.annotation.Nonnull String label) {
    this.label = label;
    this.reaconPresentFields.add(SERIALIZED_NAME_LABEL);
    return this;
  }

  /**
   * Get label
   * @return label
   */
  @javax.annotation.Nonnull
  public String getLabel() {
    return label;
  }

  public void setLabel(@javax.annotation.Nonnull String label) {
    this.label = label;
    this.reaconPresentFields.add(SERIALIZED_NAME_LABEL);
  }


  public CrmRemoteField required(@javax.annotation.Nonnull Boolean required) {
    this.required = required;
    this.reaconPresentFields.add(SERIALIZED_NAME_REQUIRED);
    return this;
  }

  /**
   * Get required
   * @return required
   */
  @javax.annotation.Nonnull
  public Boolean getRequired() {
    return required;
  }

  public void setRequired(@javax.annotation.Nonnull Boolean required) {
    this.required = required;
    this.reaconPresentFields.add(SERIALIZED_NAME_REQUIRED);
  }


  public CrmRemoteField unique(@javax.annotation.Nonnull Boolean unique) {
    this.unique = unique;
    this.reaconPresentFields.add(SERIALIZED_NAME_UNIQUE);
    return this;
  }

  /**
   * Get unique
   * @return unique
   */
  @javax.annotation.Nonnull
  public Boolean getUnique() {
    return unique;
  }

  public void setUnique(@javax.annotation.Nonnull Boolean unique) {
    this.unique = unique;
    this.reaconPresentFields.add(SERIALIZED_NAME_UNIQUE);
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the CrmRemoteField instance itself
   */
  public CrmRemoteField putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CrmRemoteField crmRemoteField = (CrmRemoteField) o;
    return Objects.equals(this.dataType, crmRemoteField.dataType) &&
        Objects.equals(this.externalId, crmRemoteField.externalId) &&
        Objects.equals(this.key, crmRemoteField.key) &&
        Objects.equals(this.label, crmRemoteField.label) &&
        Objects.equals(this.required, crmRemoteField.required) &&
        Objects.equals(this.unique, crmRemoteField.unique)&&
        Objects.equals(this.additionalProperties, crmRemoteField.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataType, externalId, key, label, required, unique, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CrmRemoteField {\n");
    sb.append("    dataType: ").append(toIndentedString(dataType)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    required: ").append(toIndentedString(required)).append("\n");
    sb.append("    unique: ").append(toIndentedString(unique)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("dataType", "externalId", "key", "label", "required", "unique"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("dataType", "externalId", "key", "label", "required", "unique"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CrmRemoteField
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CrmRemoteField.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in CrmRemoteField is not found in the empty JSON string", CrmRemoteField.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CrmRemoteField.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("dataType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `dataType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dataType").toString()));
      }
      if (!jsonObj.get("key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("key").toString()));
      }
      if (!jsonObj.get("label").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `label` to be a primitive type in the JSON string but got `%s`", jsonObj.get("label").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CrmRemoteField.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CrmRemoteField' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CrmRemoteField> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CrmRemoteField.class));

       return (TypeAdapter<T>) new TypeAdapter<CrmRemoteField>() {
           @Override
           public void write(JsonWriter out, CrmRemoteField value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             if (value.dataType == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_DATA_TYPE)) obj.add(SERIALIZED_NAME_DATA_TYPE, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_DATA_TYPE);
             }
             if (value.externalId == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_EXTERNAL_ID)) obj.add(SERIALIZED_NAME_EXTERNAL_ID, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_EXTERNAL_ID);
             }
             if (value.key == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_KEY)) obj.add(SERIALIZED_NAME_KEY, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_KEY);
             }
             if (value.label == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_LABEL)) obj.add(SERIALIZED_NAME_LABEL, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_LABEL);
             }
             if (value.required == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_REQUIRED)) obj.add(SERIALIZED_NAME_REQUIRED, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_REQUIRED);
             }
             if (value.unique == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_UNIQUE)) obj.add(SERIALIZED_NAME_UNIQUE, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_UNIQUE);
             }
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonNull()) {
                     obj.add(entry.getKey(), JsonNull.INSTANCE);
                   } else if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             boolean previousSerializeNulls = out.getSerializeNulls();
             out.setSerializeNulls(true);
             try { elementAdapter.write(out, obj); }
             finally { out.setSerializeNulls(previousSerializeNulls); }
           }

           @Override
           public CrmRemoteField read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             CrmRemoteField instance = thisAdapter.fromJsonTree(jsonObj);
             instance.reaconPresentFields.addAll(jsonObj.keySet());
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CrmRemoteField given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CrmRemoteField
   * @throws IOException if the JSON string is invalid with respect to CrmRemoteField
   */
  public static CrmRemoteField fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CrmRemoteField.class);
  }

  /**
   * Convert an instance of CrmRemoteField to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

