/*
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.reacon.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.reacon.sdk.model.IntegrationProviderListProvidersInnerConnectability;
import io.reacon.sdk.model.IntegrationProviderListProvidersInnerReadiness;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.reacon.sdk.JSON;

/**
 * IntegrationProviderListProvidersInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class IntegrationProviderListProvidersInner {
  private transient java.util.Set<String> reaconPresentFields = new java.util.HashSet<>();

  /** Whether a wire property was supplied, including an explicit null. */
  public boolean isFieldSet(String wireName) {
    switch (wireName) {
      case SERIALIZED_NAME_AUTH: return reaconPresentFields.contains(SERIALIZED_NAME_AUTH) || this.auth != null;
      case SERIALIZED_NAME_CATEGORY: return reaconPresentFields.contains(SERIALIZED_NAME_CATEGORY) || this.category != null;
      case SERIALIZED_NAME_CONNECTABILITY: return reaconPresentFields.contains(SERIALIZED_NAME_CONNECTABILITY) || this.connectability != null;
      case SERIALIZED_NAME_IMPLEMENTED: return reaconPresentFields.contains(SERIALIZED_NAME_IMPLEMENTED) || this.implemented != null;
      case SERIALIZED_NAME_NAME: return reaconPresentFields.contains(SERIALIZED_NAME_NAME) || this.name != null;
      case SERIALIZED_NAME_PROVIDER: return reaconPresentFields.contains(SERIALIZED_NAME_PROVIDER) || this.provider != null;
      case SERIALIZED_NAME_READINESS: return reaconPresentFields.contains(SERIALIZED_NAME_READINESS) || this.readiness != null;
      default: throw new IllegalArgumentException("Unknown wire property: " + wireName);
    }
  }

  /** Omit an optional property again; required properties cannot be unset. */
  public void unsetField(String wireName) {
    if (openapiRequiredFields.contains(wireName)) throw new IllegalArgumentException("Required wire property: " + wireName);
    switch (wireName) {
      case SERIALIZED_NAME_AUTH: this.auth = null; break;
      case SERIALIZED_NAME_CATEGORY: this.category = null; break;
      case SERIALIZED_NAME_CONNECTABILITY: this.connectability = null; break;
      case SERIALIZED_NAME_IMPLEMENTED: this.implemented = null; break;
      case SERIALIZED_NAME_NAME: this.name = null; break;
      case SERIALIZED_NAME_PROVIDER: this.provider = null; break;
      case SERIALIZED_NAME_READINESS: this.readiness = null; break;
      default: throw new IllegalArgumentException("Unknown wire property: " + wireName);
    }
    reaconPresentFields.remove(wireName);
  }

  public static final String SERIALIZED_NAME_AUTH = "auth";
  @SerializedName(SERIALIZED_NAME_AUTH)
  @javax.annotation.Nonnull
  private String auth;

  public static final String SERIALIZED_NAME_CATEGORY = "category";
  @SerializedName(SERIALIZED_NAME_CATEGORY)
  @javax.annotation.Nonnull
  private String category;

  public static final String SERIALIZED_NAME_CONNECTABILITY = "connectability";
  @SerializedName(SERIALIZED_NAME_CONNECTABILITY)
  @javax.annotation.Nonnull
  private IntegrationProviderListProvidersInnerConnectability connectability;

  public static final String SERIALIZED_NAME_IMPLEMENTED = "implemented";
  @SerializedName(SERIALIZED_NAME_IMPLEMENTED)
  @javax.annotation.Nonnull
  private Boolean implemented;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_PROVIDER = "provider";
  @SerializedName(SERIALIZED_NAME_PROVIDER)
  @javax.annotation.Nonnull
  private String provider;

  public static final String SERIALIZED_NAME_READINESS = "readiness";
  @SerializedName(SERIALIZED_NAME_READINESS)
  @javax.annotation.Nonnull
  private IntegrationProviderListProvidersInnerReadiness readiness;

  public IntegrationProviderListProvidersInner() {
  }

  public IntegrationProviderListProvidersInner auth(@javax.annotation.Nonnull String auth) {
    this.auth = auth;
    this.reaconPresentFields.add(SERIALIZED_NAME_AUTH);
    return this;
  }

  /**
   * Get auth
   * @return auth
   */
  @javax.annotation.Nonnull
  public String getAuth() {
    return auth;
  }

  public void setAuth(@javax.annotation.Nonnull String auth) {
    this.auth = auth;
    this.reaconPresentFields.add(SERIALIZED_NAME_AUTH);
  }


  public IntegrationProviderListProvidersInner category(@javax.annotation.Nonnull String category) {
    this.category = category;
    this.reaconPresentFields.add(SERIALIZED_NAME_CATEGORY);
    return this;
  }

  /**
   * Get category
   * @return category
   */
  @javax.annotation.Nonnull
  public String getCategory() {
    return category;
  }

  public void setCategory(@javax.annotation.Nonnull String category) {
    this.category = category;
    this.reaconPresentFields.add(SERIALIZED_NAME_CATEGORY);
  }


  public IntegrationProviderListProvidersInner connectability(@javax.annotation.Nonnull IntegrationProviderListProvidersInnerConnectability connectability) {
    this.connectability = connectability;
    this.reaconPresentFields.add(SERIALIZED_NAME_CONNECTABILITY);
    return this;
  }

  /**
   * Get connectability
   * @return connectability
   */
  @javax.annotation.Nonnull
  public IntegrationProviderListProvidersInnerConnectability getConnectability() {
    return connectability;
  }

  public void setConnectability(@javax.annotation.Nonnull IntegrationProviderListProvidersInnerConnectability connectability) {
    this.connectability = connectability;
    this.reaconPresentFields.add(SERIALIZED_NAME_CONNECTABILITY);
  }


  public IntegrationProviderListProvidersInner implemented(@javax.annotation.Nonnull Boolean implemented) {
    this.implemented = implemented;
    this.reaconPresentFields.add(SERIALIZED_NAME_IMPLEMENTED);
    return this;
  }

  /**
   * Get implemented
   * @return implemented
   */
  @javax.annotation.Nonnull
  public Boolean getImplemented() {
    return implemented;
  }

  public void setImplemented(@javax.annotation.Nonnull Boolean implemented) {
    this.implemented = implemented;
    this.reaconPresentFields.add(SERIALIZED_NAME_IMPLEMENTED);
  }


  public IntegrationProviderListProvidersInner name(@javax.annotation.Nonnull String name) {
    this.name = name;
    this.reaconPresentFields.add(SERIALIZED_NAME_NAME);
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
    this.reaconPresentFields.add(SERIALIZED_NAME_NAME);
  }


  public IntegrationProviderListProvidersInner provider(@javax.annotation.Nonnull String provider) {
    this.provider = provider;
    this.reaconPresentFields.add(SERIALIZED_NAME_PROVIDER);
    return this;
  }

  /**
   * Get provider
   * @return provider
   */
  @javax.annotation.Nonnull
  public String getProvider() {
    return provider;
  }

  public void setProvider(@javax.annotation.Nonnull String provider) {
    this.provider = provider;
    this.reaconPresentFields.add(SERIALIZED_NAME_PROVIDER);
  }


  public IntegrationProviderListProvidersInner readiness(@javax.annotation.Nonnull IntegrationProviderListProvidersInnerReadiness readiness) {
    this.readiness = readiness;
    this.reaconPresentFields.add(SERIALIZED_NAME_READINESS);
    return this;
  }

  /**
   * Get readiness
   * @return readiness
   */
  @javax.annotation.Nonnull
  public IntegrationProviderListProvidersInnerReadiness getReadiness() {
    return readiness;
  }

  public void setReadiness(@javax.annotation.Nonnull IntegrationProviderListProvidersInnerReadiness readiness) {
    this.readiness = readiness;
    this.reaconPresentFields.add(SERIALIZED_NAME_READINESS);
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the IntegrationProviderListProvidersInner instance itself
   */
  public IntegrationProviderListProvidersInner putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IntegrationProviderListProvidersInner integrationProviderListProvidersInner = (IntegrationProviderListProvidersInner) o;
    return Objects.equals(this.auth, integrationProviderListProvidersInner.auth) &&
        Objects.equals(this.category, integrationProviderListProvidersInner.category) &&
        Objects.equals(this.connectability, integrationProviderListProvidersInner.connectability) &&
        Objects.equals(this.implemented, integrationProviderListProvidersInner.implemented) &&
        Objects.equals(this.name, integrationProviderListProvidersInner.name) &&
        Objects.equals(this.provider, integrationProviderListProvidersInner.provider) &&
        Objects.equals(this.readiness, integrationProviderListProvidersInner.readiness)&&
        Objects.equals(this.additionalProperties, integrationProviderListProvidersInner.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(auth, category, connectability, implemented, name, provider, readiness, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IntegrationProviderListProvidersInner {\n");
    sb.append("    auth: ").append(toIndentedString(auth)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    connectability: ").append(toIndentedString(connectability)).append("\n");
    sb.append("    implemented: ").append(toIndentedString(implemented)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    readiness: ").append(toIndentedString(readiness)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("auth", "category", "connectability", "implemented", "name", "provider", "readiness"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("auth", "category", "connectability", "implemented", "name", "provider", "readiness"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to IntegrationProviderListProvidersInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!IntegrationProviderListProvidersInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in IntegrationProviderListProvidersInner is not found in the empty JSON string", IntegrationProviderListProvidersInner.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : IntegrationProviderListProvidersInner.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("auth").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `auth` to be a primitive type in the JSON string but got `%s`", jsonObj.get("auth").toString()));
      }
      if (!jsonObj.get("category").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `category` to be a primitive type in the JSON string but got `%s`", jsonObj.get("category").toString()));
      }
      // validate the required field `connectability`
      IntegrationProviderListProvidersInnerConnectability.validateJsonElement(jsonObj.get("connectability"));
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (!jsonObj.get("provider").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `provider` to be a primitive type in the JSON string but got `%s`", jsonObj.get("provider").toString()));
      }
      // validate the required field `readiness`
      IntegrationProviderListProvidersInnerReadiness.validateJsonElement(jsonObj.get("readiness"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!IntegrationProviderListProvidersInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'IntegrationProviderListProvidersInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<IntegrationProviderListProvidersInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(IntegrationProviderListProvidersInner.class));

       return (TypeAdapter<T>) new TypeAdapter<IntegrationProviderListProvidersInner>() {
           @Override
           public void write(JsonWriter out, IntegrationProviderListProvidersInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             if (value.auth == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_AUTH)) obj.add(SERIALIZED_NAME_AUTH, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_AUTH);
             }
             if (value.category == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_CATEGORY)) obj.add(SERIALIZED_NAME_CATEGORY, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_CATEGORY);
             }
             if (value.connectability == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_CONNECTABILITY)) obj.add(SERIALIZED_NAME_CONNECTABILITY, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_CONNECTABILITY);
             }
             if (value.implemented == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_IMPLEMENTED)) obj.add(SERIALIZED_NAME_IMPLEMENTED, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_IMPLEMENTED);
             }
             if (value.name == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_NAME)) obj.add(SERIALIZED_NAME_NAME, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_NAME);
             }
             if (value.provider == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_PROVIDER)) obj.add(SERIALIZED_NAME_PROVIDER, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_PROVIDER);
             }
             if (value.readiness == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_READINESS)) obj.add(SERIALIZED_NAME_READINESS, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_READINESS);
             }
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonNull()) {
                     obj.add(entry.getKey(), JsonNull.INSTANCE);
                   } else if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             boolean previousSerializeNulls = out.getSerializeNulls();
             out.setSerializeNulls(true);
             try { elementAdapter.write(out, obj); }
             finally { out.setSerializeNulls(previousSerializeNulls); }
           }

           @Override
           public IntegrationProviderListProvidersInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             IntegrationProviderListProvidersInner instance = thisAdapter.fromJsonTree(jsonObj);
             instance.reaconPresentFields.addAll(jsonObj.keySet());
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of IntegrationProviderListProvidersInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of IntegrationProviderListProvidersInner
   * @throws IOException if the JSON string is invalid with respect to IntegrationProviderListProvidersInner
   */
  public static IntegrationProviderListProvidersInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, IntegrationProviderListProvidersInner.class);
  }

  /**
   * Convert an instance of IntegrationProviderListProvidersInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

