/*
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.reacon.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.reacon.sdk.model.MailPostCadencesRequestNodesInnerAnyOf5ExperimentVariantsInner;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.reacon.sdk.JSON;

/**
 * Additional server validation applies; this structural schema does not express every contextual or cross-field rule.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class MailPostCadencesRequestNodesInnerAnyOf5Experiment {
  private transient java.util.Set<String> reaconPresentFields = new java.util.HashSet<>();

  /** Whether a wire property was supplied, including an explicit null. */
  public boolean isFieldSet(String wireName) {
    switch (wireName) {
      case SERIALIZED_NAME_ASSIGNMENT_UNIT: return reaconPresentFields.contains(SERIALIZED_NAME_ASSIGNMENT_UNIT) || this.assignmentUnit != null;
      case SERIALIZED_NAME_ATTRIBUTION_WINDOW_MS: return reaconPresentFields.contains(SERIALIZED_NAME_ATTRIBUTION_WINDOW_MS) || this.attributionWindowMs != null;
      case SERIALIZED_NAME_GUARDRAIL_METRICS: return reaconPresentFields.contains(SERIALIZED_NAME_GUARDRAIL_METRICS) || this.guardrailMetrics != null;
      case SERIALIZED_NAME_HYPOTHESIS: return reaconPresentFields.contains(SERIALIZED_NAME_HYPOTHESIS) || this.hypothesis != null;
      case SERIALIZED_NAME_ID: return reaconPresentFields.contains(SERIALIZED_NAME_ID) || this.id != null;
      case SERIALIZED_NAME_MINIMUM_RUNTIME_MS: return reaconPresentFields.contains(SERIALIZED_NAME_MINIMUM_RUNTIME_MS) || this.minimumRuntimeMs != null;
      case SERIALIZED_NAME_MINIMUM_SAMPLE_SIZE: return reaconPresentFields.contains(SERIALIZED_NAME_MINIMUM_SAMPLE_SIZE) || this.minimumSampleSize != null;
      case SERIALIZED_NAME_NAME: return reaconPresentFields.contains(SERIALIZED_NAME_NAME) || this.name != null;
      case SERIALIZED_NAME_PRIMARY_METRIC: return reaconPresentFields.contains(SERIALIZED_NAME_PRIMARY_METRIC) || this.primaryMetric != null;
      case SERIALIZED_NAME_VARIANTS: return reaconPresentFields.contains(SERIALIZED_NAME_VARIANTS) || this.variants != null;
      default: throw new IllegalArgumentException("Unknown wire property: " + wireName);
    }
  }

  /** Omit an optional property again; required properties cannot be unset. */
  public void unsetField(String wireName) {
    if (openapiRequiredFields.contains(wireName)) throw new IllegalArgumentException("Required wire property: " + wireName);
    switch (wireName) {
      case SERIALIZED_NAME_ASSIGNMENT_UNIT: this.assignmentUnit = null; break;
      case SERIALIZED_NAME_ATTRIBUTION_WINDOW_MS: this.attributionWindowMs = null; break;
      case SERIALIZED_NAME_GUARDRAIL_METRICS: this.guardrailMetrics = null; break;
      case SERIALIZED_NAME_HYPOTHESIS: this.hypothesis = null; break;
      case SERIALIZED_NAME_ID: this.id = null; break;
      case SERIALIZED_NAME_MINIMUM_RUNTIME_MS: this.minimumRuntimeMs = null; break;
      case SERIALIZED_NAME_MINIMUM_SAMPLE_SIZE: this.minimumSampleSize = null; break;
      case SERIALIZED_NAME_NAME: this.name = null; break;
      case SERIALIZED_NAME_PRIMARY_METRIC: this.primaryMetric = null; break;
      case SERIALIZED_NAME_VARIANTS: this.variants = null; break;
      default: throw new IllegalArgumentException("Unknown wire property: " + wireName);
    }
    reaconPresentFields.remove(wireName);
  }

  /**
   * Gets or Sets assignmentUnit
   */
  @JsonAdapter(AssignmentUnitEnum.Adapter.class)
  public enum AssignmentUnitEnum {
    CONTACT("contact");

    private String value;

    AssignmentUnitEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static AssignmentUnitEnum fromValue(String value) {
      for (AssignmentUnitEnum b : AssignmentUnitEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<AssignmentUnitEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AssignmentUnitEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AssignmentUnitEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return AssignmentUnitEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      AssignmentUnitEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_ASSIGNMENT_UNIT = "assignmentUnit";
  @SerializedName(SERIALIZED_NAME_ASSIGNMENT_UNIT)
  @javax.annotation.Nonnull
  private AssignmentUnitEnum assignmentUnit;

  public static final String SERIALIZED_NAME_ATTRIBUTION_WINDOW_MS = "attributionWindowMs";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTION_WINDOW_MS)
  @javax.annotation.Nullable
  private Integer attributionWindowMs;

  /**
   * Gets or Sets guardrailMetrics
   */
  @JsonAdapter(GuardrailMetricsEnum.Adapter.class)
  public enum GuardrailMetricsEnum {
    BOUNCE("bounce"),
    
    COMPLAINT("complaint"),
    
    UNSUBSCRIBE("unsubscribe"),
    
    PERMANENT_FAILURE("permanent_failure");

    private String value;

    GuardrailMetricsEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static GuardrailMetricsEnum fromValue(String value) {
      for (GuardrailMetricsEnum b : GuardrailMetricsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<GuardrailMetricsEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final GuardrailMetricsEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public GuardrailMetricsEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return GuardrailMetricsEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      GuardrailMetricsEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_GUARDRAIL_METRICS = "guardrailMetrics";
  @SerializedName(SERIALIZED_NAME_GUARDRAIL_METRICS)
  @javax.annotation.Nullable
  private List<GuardrailMetricsEnum> guardrailMetrics;

  public static final String SERIALIZED_NAME_HYPOTHESIS = "hypothesis";
  @SerializedName(SERIALIZED_NAME_HYPOTHESIS)
  @javax.annotation.Nullable
  private String hypothesis;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_MINIMUM_RUNTIME_MS = "minimumRuntimeMs";
  @SerializedName(SERIALIZED_NAME_MINIMUM_RUNTIME_MS)
  @javax.annotation.Nullable
  private Integer minimumRuntimeMs;

  public static final String SERIALIZED_NAME_MINIMUM_SAMPLE_SIZE = "minimumSampleSize";
  @SerializedName(SERIALIZED_NAME_MINIMUM_SAMPLE_SIZE)
  @javax.annotation.Nullable
  private Integer minimumSampleSize;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  /**
   * Gets or Sets primaryMetric
   */
  @JsonAdapter(PrimaryMetricEnum.Adapter.class)
  public enum PrimaryMetricEnum {
    POSITIVE_REPLY("positive_reply"),
    
    MEETING_BOOKED("meeting_booked"),
    
    HUMAN_REPLY("human_reply"),
    
    CLICK("click"),
    
    OPEN("open"),
    
    CUSTOM("custom");

    private String value;

    PrimaryMetricEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static PrimaryMetricEnum fromValue(String value) {
      for (PrimaryMetricEnum b : PrimaryMetricEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<PrimaryMetricEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final PrimaryMetricEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public PrimaryMetricEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return PrimaryMetricEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      PrimaryMetricEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_PRIMARY_METRIC = "primaryMetric";
  @SerializedName(SERIALIZED_NAME_PRIMARY_METRIC)
  @javax.annotation.Nullable
  private PrimaryMetricEnum primaryMetric;

  public static final String SERIALIZED_NAME_VARIANTS = "variants";
  @SerializedName(SERIALIZED_NAME_VARIANTS)
  @javax.annotation.Nonnull
  private List<MailPostCadencesRequestNodesInnerAnyOf5ExperimentVariantsInner> variants = new ArrayList<>();

  public MailPostCadencesRequestNodesInnerAnyOf5Experiment() {
  }

  public MailPostCadencesRequestNodesInnerAnyOf5Experiment assignmentUnit(@javax.annotation.Nonnull AssignmentUnitEnum assignmentUnit) {
    this.assignmentUnit = assignmentUnit;
    this.reaconPresentFields.add(SERIALIZED_NAME_ASSIGNMENT_UNIT);
    return this;
  }

  /**
   * Get assignmentUnit
   * @return assignmentUnit
   */
  @javax.annotation.Nonnull
  public AssignmentUnitEnum getAssignmentUnit() {
    return assignmentUnit;
  }

  public void setAssignmentUnit(@javax.annotation.Nonnull AssignmentUnitEnum assignmentUnit) {
    this.assignmentUnit = assignmentUnit;
    this.reaconPresentFields.add(SERIALIZED_NAME_ASSIGNMENT_UNIT);
  }


  public MailPostCadencesRequestNodesInnerAnyOf5Experiment attributionWindowMs(@javax.annotation.Nullable Integer attributionWindowMs) {
    this.attributionWindowMs = attributionWindowMs;
    this.reaconPresentFields.add(SERIALIZED_NAME_ATTRIBUTION_WINDOW_MS);
    return this;
  }

  /**
   * Get attributionWindowMs
   * minimum: 60000
   * maximum: 31536000000
   * @return attributionWindowMs
   */
  @javax.annotation.Nullable
  public Integer getAttributionWindowMs() {
    return attributionWindowMs;
  }

  public void setAttributionWindowMs(@javax.annotation.Nullable Integer attributionWindowMs) {
    this.attributionWindowMs = attributionWindowMs;
    this.reaconPresentFields.add(SERIALIZED_NAME_ATTRIBUTION_WINDOW_MS);
  }


  public MailPostCadencesRequestNodesInnerAnyOf5Experiment guardrailMetrics(@javax.annotation.Nullable List<GuardrailMetricsEnum> guardrailMetrics) {
    this.guardrailMetrics = guardrailMetrics;
    this.reaconPresentFields.add(SERIALIZED_NAME_GUARDRAIL_METRICS);
    return this;
  }

  public MailPostCadencesRequestNodesInnerAnyOf5Experiment addGuardrailMetricsItem(GuardrailMetricsEnum guardrailMetricsItem) {
    if (this.guardrailMetrics == null) {
      this.guardrailMetrics = new ArrayList<>();
    }
    this.guardrailMetrics.add(guardrailMetricsItem);
    return this;
  }

  /**
   * Get guardrailMetrics
   * @return guardrailMetrics
   */
  @javax.annotation.Nullable
  public List<GuardrailMetricsEnum> getGuardrailMetrics() {
    return guardrailMetrics;
  }

  public void setGuardrailMetrics(@javax.annotation.Nullable List<GuardrailMetricsEnum> guardrailMetrics) {
    this.guardrailMetrics = guardrailMetrics;
    this.reaconPresentFields.add(SERIALIZED_NAME_GUARDRAIL_METRICS);
  }


  public MailPostCadencesRequestNodesInnerAnyOf5Experiment hypothesis(@javax.annotation.Nullable String hypothesis) {
    this.hypothesis = hypothesis;
    this.reaconPresentFields.add(SERIALIZED_NAME_HYPOTHESIS);
    return this;
  }

  /**
   * Get hypothesis
   * @return hypothesis
   */
  @javax.annotation.Nullable
  public String getHypothesis() {
    return hypothesis;
  }

  public void setHypothesis(@javax.annotation.Nullable String hypothesis) {
    this.hypothesis = hypothesis;
    this.reaconPresentFields.add(SERIALIZED_NAME_HYPOTHESIS);
  }


  public MailPostCadencesRequestNodesInnerAnyOf5Experiment id(@javax.annotation.Nonnull String id) {
    this.id = id;
    this.reaconPresentFields.add(SERIALIZED_NAME_ID);
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
    this.reaconPresentFields.add(SERIALIZED_NAME_ID);
  }


  public MailPostCadencesRequestNodesInnerAnyOf5Experiment minimumRuntimeMs(@javax.annotation.Nullable Integer minimumRuntimeMs) {
    this.minimumRuntimeMs = minimumRuntimeMs;
    this.reaconPresentFields.add(SERIALIZED_NAME_MINIMUM_RUNTIME_MS);
    return this;
  }

  /**
   * Get minimumRuntimeMs
   * minimum: 60000
   * maximum: 31536000000
   * @return minimumRuntimeMs
   */
  @javax.annotation.Nullable
  public Integer getMinimumRuntimeMs() {
    return minimumRuntimeMs;
  }

  public void setMinimumRuntimeMs(@javax.annotation.Nullable Integer minimumRuntimeMs) {
    this.minimumRuntimeMs = minimumRuntimeMs;
    this.reaconPresentFields.add(SERIALIZED_NAME_MINIMUM_RUNTIME_MS);
  }


  public MailPostCadencesRequestNodesInnerAnyOf5Experiment minimumSampleSize(@javax.annotation.Nullable Integer minimumSampleSize) {
    this.minimumSampleSize = minimumSampleSize;
    this.reaconPresentFields.add(SERIALIZED_NAME_MINIMUM_SAMPLE_SIZE);
    return this;
  }

  /**
   * Get minimumSampleSize
   * minimum: 2
   * maximum: 100000000
   * @return minimumSampleSize
   */
  @javax.annotation.Nullable
  public Integer getMinimumSampleSize() {
    return minimumSampleSize;
  }

  public void setMinimumSampleSize(@javax.annotation.Nullable Integer minimumSampleSize) {
    this.minimumSampleSize = minimumSampleSize;
    this.reaconPresentFields.add(SERIALIZED_NAME_MINIMUM_SAMPLE_SIZE);
  }


  public MailPostCadencesRequestNodesInnerAnyOf5Experiment name(@javax.annotation.Nonnull String name) {
    this.name = name;
    this.reaconPresentFields.add(SERIALIZED_NAME_NAME);
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
    this.reaconPresentFields.add(SERIALIZED_NAME_NAME);
  }


  public MailPostCadencesRequestNodesInnerAnyOf5Experiment primaryMetric(@javax.annotation.Nullable PrimaryMetricEnum primaryMetric) {
    this.primaryMetric = primaryMetric;
    this.reaconPresentFields.add(SERIALIZED_NAME_PRIMARY_METRIC);
    return this;
  }

  /**
   * Get primaryMetric
   * @return primaryMetric
   */
  @javax.annotation.Nullable
  public PrimaryMetricEnum getPrimaryMetric() {
    return primaryMetric;
  }

  public void setPrimaryMetric(@javax.annotation.Nullable PrimaryMetricEnum primaryMetric) {
    this.primaryMetric = primaryMetric;
    this.reaconPresentFields.add(SERIALIZED_NAME_PRIMARY_METRIC);
  }


  public MailPostCadencesRequestNodesInnerAnyOf5Experiment variants(@javax.annotation.Nonnull List<MailPostCadencesRequestNodesInnerAnyOf5ExperimentVariantsInner> variants) {
    this.variants = variants;
    this.reaconPresentFields.add(SERIALIZED_NAME_VARIANTS);
    return this;
  }

  public MailPostCadencesRequestNodesInnerAnyOf5Experiment addVariantsItem(MailPostCadencesRequestNodesInnerAnyOf5ExperimentVariantsInner variantsItem) {
    if (this.variants == null) {
      this.variants = new ArrayList<>();
    }
    this.variants.add(variantsItem);
    return this;
  }

  /**
   * Get variants
   * @return variants
   */
  @javax.annotation.Nonnull
  public List<MailPostCadencesRequestNodesInnerAnyOf5ExperimentVariantsInner> getVariants() {
    return variants;
  }

  public void setVariants(@javax.annotation.Nonnull List<MailPostCadencesRequestNodesInnerAnyOf5ExperimentVariantsInner> variants) {
    this.variants = variants;
    this.reaconPresentFields.add(SERIALIZED_NAME_VARIANTS);
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MailPostCadencesRequestNodesInnerAnyOf5Experiment mailPostCadencesRequestNodesInnerAnyOf5Experiment = (MailPostCadencesRequestNodesInnerAnyOf5Experiment) o;
    return Objects.equals(this.assignmentUnit, mailPostCadencesRequestNodesInnerAnyOf5Experiment.assignmentUnit) &&
        Objects.equals(this.attributionWindowMs, mailPostCadencesRequestNodesInnerAnyOf5Experiment.attributionWindowMs) &&
        Objects.equals(this.guardrailMetrics, mailPostCadencesRequestNodesInnerAnyOf5Experiment.guardrailMetrics) &&
        Objects.equals(this.hypothesis, mailPostCadencesRequestNodesInnerAnyOf5Experiment.hypothesis) &&
        Objects.equals(this.id, mailPostCadencesRequestNodesInnerAnyOf5Experiment.id) &&
        Objects.equals(this.minimumRuntimeMs, mailPostCadencesRequestNodesInnerAnyOf5Experiment.minimumRuntimeMs) &&
        Objects.equals(this.minimumSampleSize, mailPostCadencesRequestNodesInnerAnyOf5Experiment.minimumSampleSize) &&
        Objects.equals(this.name, mailPostCadencesRequestNodesInnerAnyOf5Experiment.name) &&
        Objects.equals(this.primaryMetric, mailPostCadencesRequestNodesInnerAnyOf5Experiment.primaryMetric) &&
        Objects.equals(this.variants, mailPostCadencesRequestNodesInnerAnyOf5Experiment.variants);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assignmentUnit, attributionWindowMs, guardrailMetrics, hypothesis, id, minimumRuntimeMs, minimumSampleSize, name, primaryMetric, variants);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MailPostCadencesRequestNodesInnerAnyOf5Experiment {\n");
    sb.append("    assignmentUnit: ").append(toIndentedString(assignmentUnit)).append("\n");
    sb.append("    attributionWindowMs: ").append(toIndentedString(attributionWindowMs)).append("\n");
    sb.append("    guardrailMetrics: ").append(toIndentedString(guardrailMetrics)).append("\n");
    sb.append("    hypothesis: ").append(toIndentedString(hypothesis)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    minimumRuntimeMs: ").append(toIndentedString(minimumRuntimeMs)).append("\n");
    sb.append("    minimumSampleSize: ").append(toIndentedString(minimumSampleSize)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    primaryMetric: ").append(toIndentedString(primaryMetric)).append("\n");
    sb.append("    variants: ").append(toIndentedString(variants)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("assignmentUnit", "attributionWindowMs", "guardrailMetrics", "hypothesis", "id", "minimumRuntimeMs", "minimumSampleSize", "name", "primaryMetric", "variants"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("assignmentUnit", "id", "name", "variants"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MailPostCadencesRequestNodesInnerAnyOf5Experiment
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MailPostCadencesRequestNodesInnerAnyOf5Experiment.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in MailPostCadencesRequestNodesInnerAnyOf5Experiment is not found in the empty JSON string", MailPostCadencesRequestNodesInnerAnyOf5Experiment.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MailPostCadencesRequestNodesInnerAnyOf5Experiment.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `MailPostCadencesRequestNodesInnerAnyOf5Experiment` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : MailPostCadencesRequestNodesInnerAnyOf5Experiment.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("assignmentUnit").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `assignmentUnit` to be a primitive type in the JSON string but got `%s`", jsonObj.get("assignmentUnit").toString()));
      }
      // validate the required field `assignmentUnit`
      AssignmentUnitEnum.validateJsonElement(jsonObj.get("assignmentUnit"));
      // ensure the optional json data is an array if present
      if (jsonObj.get("guardrailMetrics") != null && !jsonObj.get("guardrailMetrics").isJsonNull() && !jsonObj.get("guardrailMetrics").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `guardrailMetrics` to be an array in the JSON string but got `%s`", jsonObj.get("guardrailMetrics").toString()));
      }
      if ((jsonObj.get("hypothesis") != null && !jsonObj.get("hypothesis").isJsonNull()) && !jsonObj.get("hypothesis").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `hypothesis` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hypothesis").toString()));
      }
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("primaryMetric") != null && !jsonObj.get("primaryMetric").isJsonNull()) && !jsonObj.get("primaryMetric").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `primaryMetric` to be a primitive type in the JSON string but got `%s`", jsonObj.get("primaryMetric").toString()));
      }
      // validate the optional field `primaryMetric`
      if (jsonObj.get("primaryMetric") != null && !jsonObj.get("primaryMetric").isJsonNull()) {
        PrimaryMetricEnum.validateJsonElement(jsonObj.get("primaryMetric"));
      }
      if (jsonObj.get("variants") != null) {
        if (!jsonObj.get("variants").isJsonArray()) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `variants` to be an array in the JSON string but got `%s`", jsonObj.get("variants").toString()));
        }
        JsonArray jsonArrayvariants = jsonObj.getAsJsonArray("variants");
        // validate the required field `variants` (array)
        for (int i = 0; i < jsonArrayvariants.size(); i++) {
          MailPostCadencesRequestNodesInnerAnyOf5ExperimentVariantsInner.validateJsonElement(jsonArrayvariants.get(i));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MailPostCadencesRequestNodesInnerAnyOf5Experiment.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MailPostCadencesRequestNodesInnerAnyOf5Experiment' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MailPostCadencesRequestNodesInnerAnyOf5Experiment> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MailPostCadencesRequestNodesInnerAnyOf5Experiment.class));

       return (TypeAdapter<T>) new TypeAdapter<MailPostCadencesRequestNodesInnerAnyOf5Experiment>() {
           @Override
           public void write(JsonWriter out, MailPostCadencesRequestNodesInnerAnyOf5Experiment value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             if (value.assignmentUnit == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_ASSIGNMENT_UNIT)) obj.add(SERIALIZED_NAME_ASSIGNMENT_UNIT, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_ASSIGNMENT_UNIT);
             }
             if (value.attributionWindowMs == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_ATTRIBUTION_WINDOW_MS)) obj.add(SERIALIZED_NAME_ATTRIBUTION_WINDOW_MS, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_ATTRIBUTION_WINDOW_MS);
             }
             if (value.guardrailMetrics == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_GUARDRAIL_METRICS)) obj.add(SERIALIZED_NAME_GUARDRAIL_METRICS, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_GUARDRAIL_METRICS);
             }
             if (value.hypothesis == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_HYPOTHESIS)) obj.add(SERIALIZED_NAME_HYPOTHESIS, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_HYPOTHESIS);
             }
             if (value.id == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_ID)) obj.add(SERIALIZED_NAME_ID, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_ID);
             }
             if (value.minimumRuntimeMs == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_MINIMUM_RUNTIME_MS)) obj.add(SERIALIZED_NAME_MINIMUM_RUNTIME_MS, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_MINIMUM_RUNTIME_MS);
             }
             if (value.minimumSampleSize == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_MINIMUM_SAMPLE_SIZE)) obj.add(SERIALIZED_NAME_MINIMUM_SAMPLE_SIZE, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_MINIMUM_SAMPLE_SIZE);
             }
             if (value.name == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_NAME)) obj.add(SERIALIZED_NAME_NAME, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_NAME);
             }
             if (value.primaryMetric == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_PRIMARY_METRIC)) obj.add(SERIALIZED_NAME_PRIMARY_METRIC, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_PRIMARY_METRIC);
             }
             if (value.variants == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_VARIANTS)) obj.add(SERIALIZED_NAME_VARIANTS, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_VARIANTS);
             }
             boolean previousSerializeNulls = out.getSerializeNulls();
             out.setSerializeNulls(true);
             try { elementAdapter.write(out, obj); }
             finally { out.setSerializeNulls(previousSerializeNulls); }
           }

           @Override
           public MailPostCadencesRequestNodesInnerAnyOf5Experiment read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             MailPostCadencesRequestNodesInnerAnyOf5Experiment instance = thisAdapter.fromJsonTree(jsonElement);
             instance.reaconPresentFields.addAll(jsonElement.getAsJsonObject().keySet());
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MailPostCadencesRequestNodesInnerAnyOf5Experiment given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MailPostCadencesRequestNodesInnerAnyOf5Experiment
   * @throws IOException if the JSON string is invalid with respect to MailPostCadencesRequestNodesInnerAnyOf5Experiment
   */
  public static MailPostCadencesRequestNodesInnerAnyOf5Experiment fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MailPostCadencesRequestNodesInnerAnyOf5Experiment.class);
  }

  /**
   * Convert an instance of MailPostCadencesRequestNodesInnerAnyOf5Experiment to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

