/*
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.reacon.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.reacon.sdk.JSON;

/**
 * MailCadenceExperimentContext
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class MailCadenceExperimentContext {
  private transient java.util.Set<String> reaconPresentFields = new java.util.HashSet<>();

  /** Whether a wire property was supplied, including an explicit null. */
  public boolean isFieldSet(String wireName) {
    switch (wireName) {
      case SERIALIZED_NAME_EXPERIMENT_ID: return reaconPresentFields.contains(SERIALIZED_NAME_EXPERIMENT_ID) || this.experimentId != null;
      case SERIALIZED_NAME_EXPERIMENT_KEY: return reaconPresentFields.contains(SERIALIZED_NAME_EXPERIMENT_KEY) || this.experimentKey != null;
      case SERIALIZED_NAME_EXPOSED_AT: return reaconPresentFields.contains(SERIALIZED_NAME_EXPOSED_AT) || this.exposedAt != null;
      case SERIALIZED_NAME_REVISION: return reaconPresentFields.contains(SERIALIZED_NAME_REVISION) || this.revision != null;
      case SERIALIZED_NAME_UNIT_ID: return reaconPresentFields.contains(SERIALIZED_NAME_UNIT_ID) || this.unitId != null;
      case SERIALIZED_NAME_VARIANT_ID: return reaconPresentFields.contains(SERIALIZED_NAME_VARIANT_ID) || this.variantId != null;
      default: throw new IllegalArgumentException("Unknown wire property: " + wireName);
    }
  }

  /** Omit an optional property again; required properties cannot be unset. */
  public void unsetField(String wireName) {
    if (openapiRequiredFields.contains(wireName)) throw new IllegalArgumentException("Required wire property: " + wireName);
    switch (wireName) {
      case SERIALIZED_NAME_EXPERIMENT_ID: this.experimentId = null; break;
      case SERIALIZED_NAME_EXPERIMENT_KEY: this.experimentKey = null; break;
      case SERIALIZED_NAME_EXPOSED_AT: this.exposedAt = null; break;
      case SERIALIZED_NAME_REVISION: this.revision = null; break;
      case SERIALIZED_NAME_UNIT_ID: this.unitId = null; break;
      case SERIALIZED_NAME_VARIANT_ID: this.variantId = null; break;
      default: throw new IllegalArgumentException("Unknown wire property: " + wireName);
    }
    reaconPresentFields.remove(wireName);
  }

  public static final String SERIALIZED_NAME_EXPERIMENT_ID = "experimentId";
  @SerializedName(SERIALIZED_NAME_EXPERIMENT_ID)
  @javax.annotation.Nonnull
  private String experimentId;

  public static final String SERIALIZED_NAME_EXPERIMENT_KEY = "experimentKey";
  @SerializedName(SERIALIZED_NAME_EXPERIMENT_KEY)
  @javax.annotation.Nonnull
  private String experimentKey;

  public static final String SERIALIZED_NAME_EXPOSED_AT = "exposedAt";
  @SerializedName(SERIALIZED_NAME_EXPOSED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime exposedAt;

  public static final String SERIALIZED_NAME_REVISION = "revision";
  @SerializedName(SERIALIZED_NAME_REVISION)
  @javax.annotation.Nonnull
  private BigDecimal revision;

  public static final String SERIALIZED_NAME_UNIT_ID = "unitId";
  @SerializedName(SERIALIZED_NAME_UNIT_ID)
  @javax.annotation.Nonnull
  private String unitId;

  public static final String SERIALIZED_NAME_VARIANT_ID = "variantId";
  @SerializedName(SERIALIZED_NAME_VARIANT_ID)
  @javax.annotation.Nonnull
  private String variantId;

  public MailCadenceExperimentContext() {
  }

  public MailCadenceExperimentContext experimentId(@javax.annotation.Nonnull String experimentId) {
    this.experimentId = experimentId;
    this.reaconPresentFields.add(SERIALIZED_NAME_EXPERIMENT_ID);
    return this;
  }

  /**
   * Get experimentId
   * @return experimentId
   */
  @javax.annotation.Nonnull
  public String getExperimentId() {
    return experimentId;
  }

  public void setExperimentId(@javax.annotation.Nonnull String experimentId) {
    this.experimentId = experimentId;
    this.reaconPresentFields.add(SERIALIZED_NAME_EXPERIMENT_ID);
  }


  public MailCadenceExperimentContext experimentKey(@javax.annotation.Nonnull String experimentKey) {
    this.experimentKey = experimentKey;
    this.reaconPresentFields.add(SERIALIZED_NAME_EXPERIMENT_KEY);
    return this;
  }

  /**
   * Get experimentKey
   * @return experimentKey
   */
  @javax.annotation.Nonnull
  public String getExperimentKey() {
    return experimentKey;
  }

  public void setExperimentKey(@javax.annotation.Nonnull String experimentKey) {
    this.experimentKey = experimentKey;
    this.reaconPresentFields.add(SERIALIZED_NAME_EXPERIMENT_KEY);
  }


  public MailCadenceExperimentContext exposedAt(@javax.annotation.Nonnull OffsetDateTime exposedAt) {
    this.exposedAt = exposedAt;
    this.reaconPresentFields.add(SERIALIZED_NAME_EXPOSED_AT);
    return this;
  }

  /**
   * Get exposedAt
   * @return exposedAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getExposedAt() {
    return exposedAt;
  }

  public void setExposedAt(@javax.annotation.Nonnull OffsetDateTime exposedAt) {
    this.exposedAt = exposedAt;
    this.reaconPresentFields.add(SERIALIZED_NAME_EXPOSED_AT);
  }


  public MailCadenceExperimentContext revision(@javax.annotation.Nonnull BigDecimal revision) {
    this.revision = revision;
    this.reaconPresentFields.add(SERIALIZED_NAME_REVISION);
    return this;
  }

  /**
   * Get revision
   * @return revision
   */
  @javax.annotation.Nonnull
  public BigDecimal getRevision() {
    return revision;
  }

  public void setRevision(@javax.annotation.Nonnull BigDecimal revision) {
    this.revision = revision;
    this.reaconPresentFields.add(SERIALIZED_NAME_REVISION);
  }


  public MailCadenceExperimentContext unitId(@javax.annotation.Nonnull String unitId) {
    this.unitId = unitId;
    this.reaconPresentFields.add(SERIALIZED_NAME_UNIT_ID);
    return this;
  }

  /**
   * Get unitId
   * @return unitId
   */
  @javax.annotation.Nonnull
  public String getUnitId() {
    return unitId;
  }

  public void setUnitId(@javax.annotation.Nonnull String unitId) {
    this.unitId = unitId;
    this.reaconPresentFields.add(SERIALIZED_NAME_UNIT_ID);
  }


  public MailCadenceExperimentContext variantId(@javax.annotation.Nonnull String variantId) {
    this.variantId = variantId;
    this.reaconPresentFields.add(SERIALIZED_NAME_VARIANT_ID);
    return this;
  }

  /**
   * Get variantId
   * @return variantId
   */
  @javax.annotation.Nonnull
  public String getVariantId() {
    return variantId;
  }

  public void setVariantId(@javax.annotation.Nonnull String variantId) {
    this.variantId = variantId;
    this.reaconPresentFields.add(SERIALIZED_NAME_VARIANT_ID);
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the MailCadenceExperimentContext instance itself
   */
  public MailCadenceExperimentContext putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MailCadenceExperimentContext mailCadenceExperimentContext = (MailCadenceExperimentContext) o;
    return Objects.equals(this.experimentId, mailCadenceExperimentContext.experimentId) &&
        Objects.equals(this.experimentKey, mailCadenceExperimentContext.experimentKey) &&
        Objects.equals(this.exposedAt, mailCadenceExperimentContext.exposedAt) &&
        Objects.equals(this.revision, mailCadenceExperimentContext.revision) &&
        Objects.equals(this.unitId, mailCadenceExperimentContext.unitId) &&
        Objects.equals(this.variantId, mailCadenceExperimentContext.variantId)&&
        Objects.equals(this.additionalProperties, mailCadenceExperimentContext.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(experimentId, experimentKey, exposedAt, revision, unitId, variantId, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MailCadenceExperimentContext {\n");
    sb.append("    experimentId: ").append(toIndentedString(experimentId)).append("\n");
    sb.append("    experimentKey: ").append(toIndentedString(experimentKey)).append("\n");
    sb.append("    exposedAt: ").append(toIndentedString(exposedAt)).append("\n");
    sb.append("    revision: ").append(toIndentedString(revision)).append("\n");
    sb.append("    unitId: ").append(toIndentedString(unitId)).append("\n");
    sb.append("    variantId: ").append(toIndentedString(variantId)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("experimentId", "experimentKey", "exposedAt", "revision", "unitId", "variantId"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("experimentId", "experimentKey", "exposedAt", "revision", "unitId", "variantId"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MailCadenceExperimentContext
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MailCadenceExperimentContext.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in MailCadenceExperimentContext is not found in the empty JSON string", MailCadenceExperimentContext.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : MailCadenceExperimentContext.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("experimentId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `experimentId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("experimentId").toString()));
      }
      if (!jsonObj.get("experimentKey").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `experimentKey` to be a primitive type in the JSON string but got `%s`", jsonObj.get("experimentKey").toString()));
      }
      if (!jsonObj.get("unitId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `unitId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("unitId").toString()));
      }
      if (!jsonObj.get("variantId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `variantId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("variantId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MailCadenceExperimentContext.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MailCadenceExperimentContext' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MailCadenceExperimentContext> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MailCadenceExperimentContext.class));

       return (TypeAdapter<T>) new TypeAdapter<MailCadenceExperimentContext>() {
           @Override
           public void write(JsonWriter out, MailCadenceExperimentContext value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             if (value.experimentId == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_EXPERIMENT_ID)) obj.add(SERIALIZED_NAME_EXPERIMENT_ID, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_EXPERIMENT_ID);
             }
             if (value.experimentKey == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_EXPERIMENT_KEY)) obj.add(SERIALIZED_NAME_EXPERIMENT_KEY, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_EXPERIMENT_KEY);
             }
             if (value.exposedAt == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_EXPOSED_AT)) obj.add(SERIALIZED_NAME_EXPOSED_AT, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_EXPOSED_AT);
             }
             if (value.revision == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_REVISION)) obj.add(SERIALIZED_NAME_REVISION, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_REVISION);
             }
             if (value.unitId == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_UNIT_ID)) obj.add(SERIALIZED_NAME_UNIT_ID, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_UNIT_ID);
             }
             if (value.variantId == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_VARIANT_ID)) obj.add(SERIALIZED_NAME_VARIANT_ID, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_VARIANT_ID);
             }
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonNull()) {
                     obj.add(entry.getKey(), JsonNull.INSTANCE);
                   } else if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             boolean previousSerializeNulls = out.getSerializeNulls();
             out.setSerializeNulls(true);
             try { elementAdapter.write(out, obj); }
             finally { out.setSerializeNulls(previousSerializeNulls); }
           }

           @Override
           public MailCadenceExperimentContext read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             MailCadenceExperimentContext instance = thisAdapter.fromJsonTree(jsonObj);
             instance.reaconPresentFields.addAll(jsonObj.keySet());
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MailCadenceExperimentContext given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MailCadenceExperimentContext
   * @throws IOException if the JSON string is invalid with respect to MailCadenceExperimentContext
   */
  public static MailCadenceExperimentContext fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MailCadenceExperimentContext.class);
  }

  /**
   * Convert an instance of MailCadenceExperimentContext to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

