/*
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.reacon.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.reacon.sdk.JSON;

/**
 * MailGetWebhooksResponse200SubscriptionsInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class MailGetWebhooksResponse200SubscriptionsInner {
  private transient java.util.Set<String> reaconPresentFields = new java.util.HashSet<>();

  /** Whether a wire property was supplied, including an explicit null. */
  public boolean isFieldSet(String wireName) {
    switch (wireName) {
      case SERIALIZED_NAME_CREATED_AT: return reaconPresentFields.contains(SERIALIZED_NAME_CREATED_AT) || this.createdAt != null;
      case SERIALIZED_NAME_CURSOR: return reaconPresentFields.contains(SERIALIZED_NAME_CURSOR) || this.cursor != null;
      case SERIALIZED_NAME_ENDPOINT: return reaconPresentFields.contains(SERIALIZED_NAME_ENDPOINT) || this.endpoint != null;
      case SERIALIZED_NAME_EVENT_TYPES: return reaconPresentFields.contains(SERIALIZED_NAME_EVENT_TYPES) || this.eventTypes != null;
      case SERIALIZED_NAME_ID: return reaconPresentFields.contains(SERIALIZED_NAME_ID) || this.id != null;
      case SERIALIZED_NAME_STATUS: return reaconPresentFields.contains(SERIALIZED_NAME_STATUS) || this.status != null;
      case SERIALIZED_NAME_TENANT_ID: return reaconPresentFields.contains(SERIALIZED_NAME_TENANT_ID) || this.tenantId != null;
      case SERIALIZED_NAME_UPDATED_AT: return reaconPresentFields.contains(SERIALIZED_NAME_UPDATED_AT) || this.updatedAt != null;
      case SERIALIZED_NAME_VERSION: return reaconPresentFields.contains(SERIALIZED_NAME_VERSION) || this.version != null;
      default: throw new IllegalArgumentException("Unknown wire property: " + wireName);
    }
  }

  /** Omit an optional property again; required properties cannot be unset. */
  public void unsetField(String wireName) {
    if (openapiRequiredFields.contains(wireName)) throw new IllegalArgumentException("Required wire property: " + wireName);
    switch (wireName) {
      case SERIALIZED_NAME_CREATED_AT: this.createdAt = null; break;
      case SERIALIZED_NAME_CURSOR: this.cursor = null; break;
      case SERIALIZED_NAME_ENDPOINT: this.endpoint = null; break;
      case SERIALIZED_NAME_EVENT_TYPES: this.eventTypes = null; break;
      case SERIALIZED_NAME_ID: this.id = null; break;
      case SERIALIZED_NAME_STATUS: this.status = null; break;
      case SERIALIZED_NAME_TENANT_ID: this.tenantId = null; break;
      case SERIALIZED_NAME_UPDATED_AT: this.updatedAt = null; break;
      case SERIALIZED_NAME_VERSION: this.version = null; break;
      default: throw new IllegalArgumentException("Unknown wire property: " + wireName);
    }
    reaconPresentFields.remove(wireName);
  }

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_CURSOR = "cursor";
  @SerializedName(SERIALIZED_NAME_CURSOR)
  @javax.annotation.Nonnull
  private BigDecimal cursor;

  public static final String SERIALIZED_NAME_ENDPOINT = "endpoint";
  @SerializedName(SERIALIZED_NAME_ENDPOINT)
  @javax.annotation.Nonnull
  private String endpoint;

  public static final String SERIALIZED_NAME_EVENT_TYPES = "eventTypes";
  @SerializedName(SERIALIZED_NAME_EVENT_TYPES)
  @javax.annotation.Nonnull
  private List<String> eventTypes = new ArrayList<>();

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nonnull
  private String status;

  public static final String SERIALIZED_NAME_TENANT_ID = "tenantId";
  @SerializedName(SERIALIZED_NAME_TENANT_ID)
  @javax.annotation.Nonnull
  private String tenantId;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime updatedAt;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  @javax.annotation.Nonnull
  private BigDecimal version;

  public MailGetWebhooksResponse200SubscriptionsInner() {
  }

  public MailGetWebhooksResponse200SubscriptionsInner createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    this.reaconPresentFields.add(SERIALIZED_NAME_CREATED_AT);
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    this.reaconPresentFields.add(SERIALIZED_NAME_CREATED_AT);
  }


  public MailGetWebhooksResponse200SubscriptionsInner cursor(@javax.annotation.Nonnull BigDecimal cursor) {
    this.cursor = cursor;
    this.reaconPresentFields.add(SERIALIZED_NAME_CURSOR);
    return this;
  }

  /**
   * Get cursor
   * @return cursor
   */
  @javax.annotation.Nonnull
  public BigDecimal getCursor() {
    return cursor;
  }

  public void setCursor(@javax.annotation.Nonnull BigDecimal cursor) {
    this.cursor = cursor;
    this.reaconPresentFields.add(SERIALIZED_NAME_CURSOR);
  }


  public MailGetWebhooksResponse200SubscriptionsInner endpoint(@javax.annotation.Nonnull String endpoint) {
    this.endpoint = endpoint;
    this.reaconPresentFields.add(SERIALIZED_NAME_ENDPOINT);
    return this;
  }

  /**
   * Get endpoint
   * @return endpoint
   */
  @javax.annotation.Nonnull
  public String getEndpoint() {
    return endpoint;
  }

  public void setEndpoint(@javax.annotation.Nonnull String endpoint) {
    this.endpoint = endpoint;
    this.reaconPresentFields.add(SERIALIZED_NAME_ENDPOINT);
  }


  public MailGetWebhooksResponse200SubscriptionsInner eventTypes(@javax.annotation.Nonnull List<String> eventTypes) {
    this.eventTypes = eventTypes;
    this.reaconPresentFields.add(SERIALIZED_NAME_EVENT_TYPES);
    return this;
  }

  public MailGetWebhooksResponse200SubscriptionsInner addEventTypesItem(String eventTypesItem) {
    if (this.eventTypes == null) {
      this.eventTypes = new ArrayList<>();
    }
    this.eventTypes.add(eventTypesItem);
    return this;
  }

  /**
   * Get eventTypes
   * @return eventTypes
   */
  @javax.annotation.Nonnull
  public List<String> getEventTypes() {
    return eventTypes;
  }

  public void setEventTypes(@javax.annotation.Nonnull List<String> eventTypes) {
    this.eventTypes = eventTypes;
    this.reaconPresentFields.add(SERIALIZED_NAME_EVENT_TYPES);
  }


  public MailGetWebhooksResponse200SubscriptionsInner id(@javax.annotation.Nonnull String id) {
    this.id = id;
    this.reaconPresentFields.add(SERIALIZED_NAME_ID);
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
    this.reaconPresentFields.add(SERIALIZED_NAME_ID);
  }


  public MailGetWebhooksResponse200SubscriptionsInner status(@javax.annotation.Nonnull String status) {
    this.status = status;
    this.reaconPresentFields.add(SERIALIZED_NAME_STATUS);
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  public String getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nonnull String status) {
    this.status = status;
    this.reaconPresentFields.add(SERIALIZED_NAME_STATUS);
  }


  public MailGetWebhooksResponse200SubscriptionsInner tenantId(@javax.annotation.Nonnull String tenantId) {
    this.tenantId = tenantId;
    this.reaconPresentFields.add(SERIALIZED_NAME_TENANT_ID);
    return this;
  }

  /**
   * Get tenantId
   * @return tenantId
   */
  @javax.annotation.Nonnull
  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(@javax.annotation.Nonnull String tenantId) {
    this.tenantId = tenantId;
    this.reaconPresentFields.add(SERIALIZED_NAME_TENANT_ID);
  }


  public MailGetWebhooksResponse200SubscriptionsInner updatedAt(@javax.annotation.Nonnull OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    this.reaconPresentFields.add(SERIALIZED_NAME_UPDATED_AT);
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(@javax.annotation.Nonnull OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    this.reaconPresentFields.add(SERIALIZED_NAME_UPDATED_AT);
  }


  public MailGetWebhooksResponse200SubscriptionsInner version(@javax.annotation.Nonnull BigDecimal version) {
    this.version = version;
    this.reaconPresentFields.add(SERIALIZED_NAME_VERSION);
    return this;
  }

  /**
   * Get version
   * @return version
   */
  @javax.annotation.Nonnull
  public BigDecimal getVersion() {
    return version;
  }

  public void setVersion(@javax.annotation.Nonnull BigDecimal version) {
    this.version = version;
    this.reaconPresentFields.add(SERIALIZED_NAME_VERSION);
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the MailGetWebhooksResponse200SubscriptionsInner instance itself
   */
  public MailGetWebhooksResponse200SubscriptionsInner putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MailGetWebhooksResponse200SubscriptionsInner mailGetWebhooksResponse200SubscriptionsInner = (MailGetWebhooksResponse200SubscriptionsInner) o;
    return Objects.equals(this.createdAt, mailGetWebhooksResponse200SubscriptionsInner.createdAt) &&
        Objects.equals(this.cursor, mailGetWebhooksResponse200SubscriptionsInner.cursor) &&
        Objects.equals(this.endpoint, mailGetWebhooksResponse200SubscriptionsInner.endpoint) &&
        Objects.equals(this.eventTypes, mailGetWebhooksResponse200SubscriptionsInner.eventTypes) &&
        Objects.equals(this.id, mailGetWebhooksResponse200SubscriptionsInner.id) &&
        Objects.equals(this.status, mailGetWebhooksResponse200SubscriptionsInner.status) &&
        Objects.equals(this.tenantId, mailGetWebhooksResponse200SubscriptionsInner.tenantId) &&
        Objects.equals(this.updatedAt, mailGetWebhooksResponse200SubscriptionsInner.updatedAt) &&
        Objects.equals(this.version, mailGetWebhooksResponse200SubscriptionsInner.version)&&
        Objects.equals(this.additionalProperties, mailGetWebhooksResponse200SubscriptionsInner.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdAt, cursor, endpoint, eventTypes, id, status, tenantId, updatedAt, version, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MailGetWebhooksResponse200SubscriptionsInner {\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    cursor: ").append(toIndentedString(cursor)).append("\n");
    sb.append("    endpoint: ").append(toIndentedString(endpoint)).append("\n");
    sb.append("    eventTypes: ").append(toIndentedString(eventTypes)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("createdAt", "cursor", "endpoint", "eventTypes", "id", "status", "tenantId", "updatedAt", "version"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("createdAt", "cursor", "endpoint", "eventTypes", "id", "status", "tenantId", "updatedAt", "version"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MailGetWebhooksResponse200SubscriptionsInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MailGetWebhooksResponse200SubscriptionsInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in MailGetWebhooksResponse200SubscriptionsInner is not found in the empty JSON string", MailGetWebhooksResponse200SubscriptionsInner.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : MailGetWebhooksResponse200SubscriptionsInner.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("endpoint").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `endpoint` to be a primitive type in the JSON string but got `%s`", jsonObj.get("endpoint").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("eventTypes") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("eventTypes").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `eventTypes` to be an array in the JSON string but got `%s`", jsonObj.get("eventTypes").toString()));
      }
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if (!jsonObj.get("tenantId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `tenantId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tenantId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MailGetWebhooksResponse200SubscriptionsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MailGetWebhooksResponse200SubscriptionsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MailGetWebhooksResponse200SubscriptionsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MailGetWebhooksResponse200SubscriptionsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<MailGetWebhooksResponse200SubscriptionsInner>() {
           @Override
           public void write(JsonWriter out, MailGetWebhooksResponse200SubscriptionsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             if (value.createdAt == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_CREATED_AT)) obj.add(SERIALIZED_NAME_CREATED_AT, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_CREATED_AT);
             }
             if (value.cursor == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_CURSOR)) obj.add(SERIALIZED_NAME_CURSOR, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_CURSOR);
             }
             if (value.endpoint == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_ENDPOINT)) obj.add(SERIALIZED_NAME_ENDPOINT, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_ENDPOINT);
             }
             if (value.eventTypes == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_EVENT_TYPES)) obj.add(SERIALIZED_NAME_EVENT_TYPES, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_EVENT_TYPES);
             }
             if (value.id == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_ID)) obj.add(SERIALIZED_NAME_ID, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_ID);
             }
             if (value.status == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_STATUS)) obj.add(SERIALIZED_NAME_STATUS, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_STATUS);
             }
             if (value.tenantId == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_TENANT_ID)) obj.add(SERIALIZED_NAME_TENANT_ID, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_TENANT_ID);
             }
             if (value.updatedAt == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_UPDATED_AT)) obj.add(SERIALIZED_NAME_UPDATED_AT, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_UPDATED_AT);
             }
             if (value.version == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_VERSION)) obj.add(SERIALIZED_NAME_VERSION, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_VERSION);
             }
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonNull()) {
                     obj.add(entry.getKey(), JsonNull.INSTANCE);
                   } else if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             boolean previousSerializeNulls = out.getSerializeNulls();
             out.setSerializeNulls(true);
             try { elementAdapter.write(out, obj); }
             finally { out.setSerializeNulls(previousSerializeNulls); }
           }

           @Override
           public MailGetWebhooksResponse200SubscriptionsInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             MailGetWebhooksResponse200SubscriptionsInner instance = thisAdapter.fromJsonTree(jsonObj);
             instance.reaconPresentFields.addAll(jsonObj.keySet());
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MailGetWebhooksResponse200SubscriptionsInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MailGetWebhooksResponse200SubscriptionsInner
   * @throws IOException if the JSON string is invalid with respect to MailGetWebhooksResponse200SubscriptionsInner
   */
  public static MailGetWebhooksResponse200SubscriptionsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MailGetWebhooksResponse200SubscriptionsInner.class);
  }

  /**
   * Convert an instance of MailGetWebhooksResponse200SubscriptionsInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

