/*
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.reacon.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.reacon.sdk.model.MailCampaignDraftRecord;
import io.reacon.sdk.model.MailPostCampaignsByCampaignIdLaunchResponse200Campaign;
import io.reacon.sdk.model.MailSequenceRunRecord;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.reacon.sdk.JSON;

/**
 * MailPostCampaignsByCampaignIdLaunchResponse200AnyOf1
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class MailPostCampaignsByCampaignIdLaunchResponse200AnyOf1 {
  private transient java.util.Set<String> reaconPresentFields = new java.util.HashSet<>();

  /** Whether a wire property was supplied, including an explicit null. */
  public boolean isFieldSet(String wireName) {
    switch (wireName) {
      case SERIALIZED_NAME_CAMPAIGN: return reaconPresentFields.contains(SERIALIZED_NAME_CAMPAIGN) || this.campaign != null;
      case SERIALIZED_NAME_DRAFT: return reaconPresentFields.contains(SERIALIZED_NAME_DRAFT) || this.draft != null;
      case SERIALIZED_NAME_SEQUENCES: return reaconPresentFields.contains(SERIALIZED_NAME_SEQUENCES) || this.sequences != null;
      default: throw new IllegalArgumentException("Unknown wire property: " + wireName);
    }
  }

  /** Omit an optional property again; required properties cannot be unset. */
  public void unsetField(String wireName) {
    if (openapiRequiredFields.contains(wireName)) throw new IllegalArgumentException("Required wire property: " + wireName);
    switch (wireName) {
      case SERIALIZED_NAME_CAMPAIGN: this.campaign = null; break;
      case SERIALIZED_NAME_DRAFT: this.draft = null; break;
      case SERIALIZED_NAME_SEQUENCES: this.sequences = null; break;
      default: throw new IllegalArgumentException("Unknown wire property: " + wireName);
    }
    reaconPresentFields.remove(wireName);
  }

  public static final String SERIALIZED_NAME_CAMPAIGN = "campaign";
  @SerializedName(SERIALIZED_NAME_CAMPAIGN)
  @javax.annotation.Nonnull
  private MailPostCampaignsByCampaignIdLaunchResponse200Campaign campaign;

  public static final String SERIALIZED_NAME_DRAFT = "draft";
  @SerializedName(SERIALIZED_NAME_DRAFT)
  @javax.annotation.Nonnull
  private MailCampaignDraftRecord draft;

  public static final String SERIALIZED_NAME_SEQUENCES = "sequences";
  @SerializedName(SERIALIZED_NAME_SEQUENCES)
  @javax.annotation.Nonnull
  private List<MailSequenceRunRecord> sequences = new ArrayList<>();

  public MailPostCampaignsByCampaignIdLaunchResponse200AnyOf1() {
  }

  public MailPostCampaignsByCampaignIdLaunchResponse200AnyOf1 campaign(@javax.annotation.Nonnull MailPostCampaignsByCampaignIdLaunchResponse200Campaign campaign) {
    this.campaign = campaign;
    this.reaconPresentFields.add(SERIALIZED_NAME_CAMPAIGN);
    return this;
  }

  /**
   * Get campaign
   * @return campaign
   */
  @javax.annotation.Nonnull
  public MailPostCampaignsByCampaignIdLaunchResponse200Campaign getCampaign() {
    return campaign;
  }

  public void setCampaign(@javax.annotation.Nonnull MailPostCampaignsByCampaignIdLaunchResponse200Campaign campaign) {
    this.campaign = campaign;
    this.reaconPresentFields.add(SERIALIZED_NAME_CAMPAIGN);
  }


  public MailPostCampaignsByCampaignIdLaunchResponse200AnyOf1 draft(@javax.annotation.Nonnull MailCampaignDraftRecord draft) {
    this.draft = draft;
    this.reaconPresentFields.add(SERIALIZED_NAME_DRAFT);
    return this;
  }

  /**
   * Get draft
   * @return draft
   */
  @javax.annotation.Nonnull
  public MailCampaignDraftRecord getDraft() {
    return draft;
  }

  public void setDraft(@javax.annotation.Nonnull MailCampaignDraftRecord draft) {
    this.draft = draft;
    this.reaconPresentFields.add(SERIALIZED_NAME_DRAFT);
  }


  public MailPostCampaignsByCampaignIdLaunchResponse200AnyOf1 sequences(@javax.annotation.Nonnull List<MailSequenceRunRecord> sequences) {
    this.sequences = sequences;
    this.reaconPresentFields.add(SERIALIZED_NAME_SEQUENCES);
    return this;
  }

  public MailPostCampaignsByCampaignIdLaunchResponse200AnyOf1 addSequencesItem(MailSequenceRunRecord sequencesItem) {
    if (this.sequences == null) {
      this.sequences = new ArrayList<>();
    }
    this.sequences.add(sequencesItem);
    return this;
  }

  /**
   * Get sequences
   * @return sequences
   */
  @javax.annotation.Nonnull
  public List<MailSequenceRunRecord> getSequences() {
    return sequences;
  }

  public void setSequences(@javax.annotation.Nonnull List<MailSequenceRunRecord> sequences) {
    this.sequences = sequences;
    this.reaconPresentFields.add(SERIALIZED_NAME_SEQUENCES);
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the MailPostCampaignsByCampaignIdLaunchResponse200AnyOf1 instance itself
   */
  public MailPostCampaignsByCampaignIdLaunchResponse200AnyOf1 putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MailPostCampaignsByCampaignIdLaunchResponse200AnyOf1 mailPostCampaignsByCampaignIdLaunchResponse200AnyOf1 = (MailPostCampaignsByCampaignIdLaunchResponse200AnyOf1) o;
    return Objects.equals(this.campaign, mailPostCampaignsByCampaignIdLaunchResponse200AnyOf1.campaign) &&
        Objects.equals(this.draft, mailPostCampaignsByCampaignIdLaunchResponse200AnyOf1.draft) &&
        Objects.equals(this.sequences, mailPostCampaignsByCampaignIdLaunchResponse200AnyOf1.sequences)&&
        Objects.equals(this.additionalProperties, mailPostCampaignsByCampaignIdLaunchResponse200AnyOf1.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(campaign, draft, sequences, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MailPostCampaignsByCampaignIdLaunchResponse200AnyOf1 {\n");
    sb.append("    campaign: ").append(toIndentedString(campaign)).append("\n");
    sb.append("    draft: ").append(toIndentedString(draft)).append("\n");
    sb.append("    sequences: ").append(toIndentedString(sequences)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("campaign", "draft", "sequences"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("campaign", "draft", "sequences"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MailPostCampaignsByCampaignIdLaunchResponse200AnyOf1
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MailPostCampaignsByCampaignIdLaunchResponse200AnyOf1.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in MailPostCampaignsByCampaignIdLaunchResponse200AnyOf1 is not found in the empty JSON string", MailPostCampaignsByCampaignIdLaunchResponse200AnyOf1.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : MailPostCampaignsByCampaignIdLaunchResponse200AnyOf1.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `campaign`
      MailPostCampaignsByCampaignIdLaunchResponse200Campaign.validateJsonElement(jsonObj.get("campaign"));
      // validate the required field `draft`
      MailCampaignDraftRecord.validateJsonElement(jsonObj.get("draft"));
      if (jsonObj.get("sequences") != null) {
        if (!jsonObj.get("sequences").isJsonArray()) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `sequences` to be an array in the JSON string but got `%s`", jsonObj.get("sequences").toString()));
        }
        JsonArray jsonArraysequences = jsonObj.getAsJsonArray("sequences");
        // validate the required field `sequences` (array)
        for (int i = 0; i < jsonArraysequences.size(); i++) {
          MailSequenceRunRecord.validateJsonElement(jsonArraysequences.get(i));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MailPostCampaignsByCampaignIdLaunchResponse200AnyOf1.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MailPostCampaignsByCampaignIdLaunchResponse200AnyOf1' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MailPostCampaignsByCampaignIdLaunchResponse200AnyOf1> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MailPostCampaignsByCampaignIdLaunchResponse200AnyOf1.class));

       return (TypeAdapter<T>) new TypeAdapter<MailPostCampaignsByCampaignIdLaunchResponse200AnyOf1>() {
           @Override
           public void write(JsonWriter out, MailPostCampaignsByCampaignIdLaunchResponse200AnyOf1 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             if (value.campaign == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_CAMPAIGN)) obj.add(SERIALIZED_NAME_CAMPAIGN, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_CAMPAIGN);
             }
             if (value.draft == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_DRAFT)) obj.add(SERIALIZED_NAME_DRAFT, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_DRAFT);
             }
             if (value.sequences == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_SEQUENCES)) obj.add(SERIALIZED_NAME_SEQUENCES, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_SEQUENCES);
             }
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonNull()) {
                     obj.add(entry.getKey(), JsonNull.INSTANCE);
                   } else if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             boolean previousSerializeNulls = out.getSerializeNulls();
             out.setSerializeNulls(true);
             try { elementAdapter.write(out, obj); }
             finally { out.setSerializeNulls(previousSerializeNulls); }
           }

           @Override
           public MailPostCampaignsByCampaignIdLaunchResponse200AnyOf1 read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             MailPostCampaignsByCampaignIdLaunchResponse200AnyOf1 instance = thisAdapter.fromJsonTree(jsonObj);
             instance.reaconPresentFields.addAll(jsonObj.keySet());
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MailPostCampaignsByCampaignIdLaunchResponse200AnyOf1 given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MailPostCampaignsByCampaignIdLaunchResponse200AnyOf1
   * @throws IOException if the JSON string is invalid with respect to MailPostCampaignsByCampaignIdLaunchResponse200AnyOf1
   */
  public static MailPostCampaignsByCampaignIdLaunchResponse200AnyOf1 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MailPostCampaignsByCampaignIdLaunchResponse200AnyOf1.class);
  }

  /**
   * Convert an instance of MailPostCampaignsByCampaignIdLaunchResponse200AnyOf1 to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

