/*
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.reacon.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.reacon.sdk.model.MailGetDeliverabilityResponse200PoolsInner;
import io.reacon.sdk.model.MailMailboxHealthRecord;
import io.reacon.sdk.model.MailMailboxRecord;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.reacon.sdk.JSON;

/**
 * MailGetDeliverabilityResponse200
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class MailGetDeliverabilityResponse200 {
  private transient java.util.Set<String> reaconPresentFields = new java.util.HashSet<>();

  /** Whether a wire property was supplied, including an explicit null. */
  public boolean isFieldSet(String wireName) {
    switch (wireName) {
      case SERIALIZED_NAME_HEALTH: return reaconPresentFields.contains(SERIALIZED_NAME_HEALTH) || this.health != null;
      case SERIALIZED_NAME_MAILBOXES: return reaconPresentFields.contains(SERIALIZED_NAME_MAILBOXES) || this.mailboxes != null;
      case SERIALIZED_NAME_POOLS: return reaconPresentFields.contains(SERIALIZED_NAME_POOLS) || this.pools != null;
      default: throw new IllegalArgumentException("Unknown wire property: " + wireName);
    }
  }

  /** Omit an optional property again; required properties cannot be unset. */
  public void unsetField(String wireName) {
    if (openapiRequiredFields.contains(wireName)) throw new IllegalArgumentException("Required wire property: " + wireName);
    switch (wireName) {
      case SERIALIZED_NAME_HEALTH: this.health = null; break;
      case SERIALIZED_NAME_MAILBOXES: this.mailboxes = null; break;
      case SERIALIZED_NAME_POOLS: this.pools = null; break;
      default: throw new IllegalArgumentException("Unknown wire property: " + wireName);
    }
    reaconPresentFields.remove(wireName);
  }

  public static final String SERIALIZED_NAME_HEALTH = "health";
  @SerializedName(SERIALIZED_NAME_HEALTH)
  @javax.annotation.Nonnull
  private List<MailMailboxHealthRecord> health = new ArrayList<>();

  public static final String SERIALIZED_NAME_MAILBOXES = "mailboxes";
  @SerializedName(SERIALIZED_NAME_MAILBOXES)
  @javax.annotation.Nonnull
  private List<MailMailboxRecord> mailboxes = new ArrayList<>();

  public static final String SERIALIZED_NAME_POOLS = "pools";
  @SerializedName(SERIALIZED_NAME_POOLS)
  @javax.annotation.Nonnull
  private List<MailGetDeliverabilityResponse200PoolsInner> pools = new ArrayList<>();

  public MailGetDeliverabilityResponse200() {
  }

  public MailGetDeliverabilityResponse200 health(@javax.annotation.Nonnull List<MailMailboxHealthRecord> health) {
    this.health = health;
    this.reaconPresentFields.add(SERIALIZED_NAME_HEALTH);
    return this;
  }

  public MailGetDeliverabilityResponse200 addHealthItem(MailMailboxHealthRecord healthItem) {
    if (this.health == null) {
      this.health = new ArrayList<>();
    }
    this.health.add(healthItem);
    return this;
  }

  /**
   * Get health
   * @return health
   */
  @javax.annotation.Nonnull
  public List<MailMailboxHealthRecord> getHealth() {
    return health;
  }

  public void setHealth(@javax.annotation.Nonnull List<MailMailboxHealthRecord> health) {
    this.health = health;
    this.reaconPresentFields.add(SERIALIZED_NAME_HEALTH);
  }


  public MailGetDeliverabilityResponse200 mailboxes(@javax.annotation.Nonnull List<MailMailboxRecord> mailboxes) {
    this.mailboxes = mailboxes;
    this.reaconPresentFields.add(SERIALIZED_NAME_MAILBOXES);
    return this;
  }

  public MailGetDeliverabilityResponse200 addMailboxesItem(MailMailboxRecord mailboxesItem) {
    if (this.mailboxes == null) {
      this.mailboxes = new ArrayList<>();
    }
    this.mailboxes.add(mailboxesItem);
    return this;
  }

  /**
   * Get mailboxes
   * @return mailboxes
   */
  @javax.annotation.Nonnull
  public List<MailMailboxRecord> getMailboxes() {
    return mailboxes;
  }

  public void setMailboxes(@javax.annotation.Nonnull List<MailMailboxRecord> mailboxes) {
    this.mailboxes = mailboxes;
    this.reaconPresentFields.add(SERIALIZED_NAME_MAILBOXES);
  }


  public MailGetDeliverabilityResponse200 pools(@javax.annotation.Nonnull List<MailGetDeliverabilityResponse200PoolsInner> pools) {
    this.pools = pools;
    this.reaconPresentFields.add(SERIALIZED_NAME_POOLS);
    return this;
  }

  public MailGetDeliverabilityResponse200 addPoolsItem(MailGetDeliverabilityResponse200PoolsInner poolsItem) {
    if (this.pools == null) {
      this.pools = new ArrayList<>();
    }
    this.pools.add(poolsItem);
    return this;
  }

  /**
   * Get pools
   * @return pools
   */
  @javax.annotation.Nonnull
  public List<MailGetDeliverabilityResponse200PoolsInner> getPools() {
    return pools;
  }

  public void setPools(@javax.annotation.Nonnull List<MailGetDeliverabilityResponse200PoolsInner> pools) {
    this.pools = pools;
    this.reaconPresentFields.add(SERIALIZED_NAME_POOLS);
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the MailGetDeliverabilityResponse200 instance itself
   */
  public MailGetDeliverabilityResponse200 putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MailGetDeliverabilityResponse200 mailGetDeliverabilityResponse200 = (MailGetDeliverabilityResponse200) o;
    return Objects.equals(this.health, mailGetDeliverabilityResponse200.health) &&
        Objects.equals(this.mailboxes, mailGetDeliverabilityResponse200.mailboxes) &&
        Objects.equals(this.pools, mailGetDeliverabilityResponse200.pools)&&
        Objects.equals(this.additionalProperties, mailGetDeliverabilityResponse200.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(health, mailboxes, pools, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MailGetDeliverabilityResponse200 {\n");
    sb.append("    health: ").append(toIndentedString(health)).append("\n");
    sb.append("    mailboxes: ").append(toIndentedString(mailboxes)).append("\n");
    sb.append("    pools: ").append(toIndentedString(pools)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("health", "mailboxes", "pools"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("health", "mailboxes", "pools"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MailGetDeliverabilityResponse200
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MailGetDeliverabilityResponse200.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in MailGetDeliverabilityResponse200 is not found in the empty JSON string", MailGetDeliverabilityResponse200.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : MailGetDeliverabilityResponse200.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("health") != null) {
        if (!jsonObj.get("health").isJsonArray()) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `health` to be an array in the JSON string but got `%s`", jsonObj.get("health").toString()));
        }
        JsonArray jsonArrayhealth = jsonObj.getAsJsonArray("health");
        // validate the required field `health` (array)
        for (int i = 0; i < jsonArrayhealth.size(); i++) {
          MailMailboxHealthRecord.validateJsonElement(jsonArrayhealth.get(i));
        }
      }
      if (jsonObj.get("mailboxes") != null) {
        if (!jsonObj.get("mailboxes").isJsonArray()) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `mailboxes` to be an array in the JSON string but got `%s`", jsonObj.get("mailboxes").toString()));
        }
        JsonArray jsonArraymailboxes = jsonObj.getAsJsonArray("mailboxes");
        // validate the required field `mailboxes` (array)
        for (int i = 0; i < jsonArraymailboxes.size(); i++) {
          MailMailboxRecord.validateJsonElement(jsonArraymailboxes.get(i));
        }
      }
      if (jsonObj.get("pools") != null) {
        if (!jsonObj.get("pools").isJsonArray()) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `pools` to be an array in the JSON string but got `%s`", jsonObj.get("pools").toString()));
        }
        JsonArray jsonArraypools = jsonObj.getAsJsonArray("pools");
        // validate the required field `pools` (array)
        for (int i = 0; i < jsonArraypools.size(); i++) {
          MailGetDeliverabilityResponse200PoolsInner.validateJsonElement(jsonArraypools.get(i));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MailGetDeliverabilityResponse200.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MailGetDeliverabilityResponse200' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MailGetDeliverabilityResponse200> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MailGetDeliverabilityResponse200.class));

       return (TypeAdapter<T>) new TypeAdapter<MailGetDeliverabilityResponse200>() {
           @Override
           public void write(JsonWriter out, MailGetDeliverabilityResponse200 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             if (value.health == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_HEALTH)) obj.add(SERIALIZED_NAME_HEALTH, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_HEALTH);
             }
             if (value.mailboxes == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_MAILBOXES)) obj.add(SERIALIZED_NAME_MAILBOXES, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_MAILBOXES);
             }
             if (value.pools == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_POOLS)) obj.add(SERIALIZED_NAME_POOLS, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_POOLS);
             }
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonNull()) {
                     obj.add(entry.getKey(), JsonNull.INSTANCE);
                   } else if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             boolean previousSerializeNulls = out.getSerializeNulls();
             out.setSerializeNulls(true);
             try { elementAdapter.write(out, obj); }
             finally { out.setSerializeNulls(previousSerializeNulls); }
           }

           @Override
           public MailGetDeliverabilityResponse200 read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             MailGetDeliverabilityResponse200 instance = thisAdapter.fromJsonTree(jsonObj);
             instance.reaconPresentFields.addAll(jsonObj.keySet());
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MailGetDeliverabilityResponse200 given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MailGetDeliverabilityResponse200
   * @throws IOException if the JSON string is invalid with respect to MailGetDeliverabilityResponse200
   */
  public static MailGetDeliverabilityResponse200 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MailGetDeliverabilityResponse200.class);
  }

  /**
   * Convert an instance of MailGetDeliverabilityResponse200 to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

