/*
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.reacon.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.reacon.sdk.model.MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner;
import io.reacon.sdk.model.MailPatchCampaignsByCampaignIdRequestPolicySendingWindowsInner;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.reacon.sdk.JSON;

/**
 * MailPatchCampaignsByCampaignIdRequestPolicy
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class MailPatchCampaignsByCampaignIdRequestPolicy {
  private transient java.util.Set<String> reaconPresentFields = new java.util.HashSet<>();

  /** Whether a wire property was supplied, including an explicit null. */
  public boolean isFieldSet(String wireName) {
    switch (wireName) {
      case SERIALIZED_NAME_DOMAIN_QUOTAS: return reaconPresentFields.contains(SERIALIZED_NAME_DOMAIN_QUOTAS) || this.domainQuotas != null;
      case SERIALIZED_NAME_MAILBOX_QUOTAS: return reaconPresentFields.contains(SERIALIZED_NAME_MAILBOX_QUOTAS) || this.mailboxQuotas != null;
      case SERIALIZED_NAME_RECIPIENT_COOLDOWN_MS: return reaconPresentFields.contains(SERIALIZED_NAME_RECIPIENT_COOLDOWN_MS) || this.recipientCooldownMs != null;
      case SERIALIZED_NAME_RECIPIENT_QUOTAS: return reaconPresentFields.contains(SERIALIZED_NAME_RECIPIENT_QUOTAS) || this.recipientQuotas != null;
      case SERIALIZED_NAME_SENDING_WINDOWS: return reaconPresentFields.contains(SERIALIZED_NAME_SENDING_WINDOWS) || this.sendingWindows != null;
      case SERIALIZED_NAME_TENANT_QUOTAS: return reaconPresentFields.contains(SERIALIZED_NAME_TENANT_QUOTAS) || this.tenantQuotas != null;
      case SERIALIZED_NAME_TIME_ZONE: return reaconPresentFields.contains(SERIALIZED_NAME_TIME_ZONE) || this.timeZone != null;
      default: throw new IllegalArgumentException("Unknown wire property: " + wireName);
    }
  }

  /** Omit an optional property again; required properties cannot be unset. */
  public void unsetField(String wireName) {
    if (openapiRequiredFields.contains(wireName)) throw new IllegalArgumentException("Required wire property: " + wireName);
    switch (wireName) {
      case SERIALIZED_NAME_DOMAIN_QUOTAS: this.domainQuotas = null; break;
      case SERIALIZED_NAME_MAILBOX_QUOTAS: this.mailboxQuotas = null; break;
      case SERIALIZED_NAME_RECIPIENT_COOLDOWN_MS: this.recipientCooldownMs = null; break;
      case SERIALIZED_NAME_RECIPIENT_QUOTAS: this.recipientQuotas = null; break;
      case SERIALIZED_NAME_SENDING_WINDOWS: this.sendingWindows = null; break;
      case SERIALIZED_NAME_TENANT_QUOTAS: this.tenantQuotas = null; break;
      case SERIALIZED_NAME_TIME_ZONE: this.timeZone = null; break;
      default: throw new IllegalArgumentException("Unknown wire property: " + wireName);
    }
    reaconPresentFields.remove(wireName);
  }

  public static final String SERIALIZED_NAME_DOMAIN_QUOTAS = "domainQuotas";
  @SerializedName(SERIALIZED_NAME_DOMAIN_QUOTAS)
  @javax.annotation.Nullable
  private List<MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner> domainQuotas;

  public static final String SERIALIZED_NAME_MAILBOX_QUOTAS = "mailboxQuotas";
  @SerializedName(SERIALIZED_NAME_MAILBOX_QUOTAS)
  @javax.annotation.Nullable
  private List<MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner> mailboxQuotas;

  public static final String SERIALIZED_NAME_RECIPIENT_COOLDOWN_MS = "recipientCooldownMs";
  @SerializedName(SERIALIZED_NAME_RECIPIENT_COOLDOWN_MS)
  @javax.annotation.Nullable
  private Integer recipientCooldownMs;

  public static final String SERIALIZED_NAME_RECIPIENT_QUOTAS = "recipientQuotas";
  @SerializedName(SERIALIZED_NAME_RECIPIENT_QUOTAS)
  @javax.annotation.Nullable
  private List<MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner> recipientQuotas;

  public static final String SERIALIZED_NAME_SENDING_WINDOWS = "sendingWindows";
  @SerializedName(SERIALIZED_NAME_SENDING_WINDOWS)
  @javax.annotation.Nullable
  private List<MailPatchCampaignsByCampaignIdRequestPolicySendingWindowsInner> sendingWindows;

  public static final String SERIALIZED_NAME_TENANT_QUOTAS = "tenantQuotas";
  @SerializedName(SERIALIZED_NAME_TENANT_QUOTAS)
  @javax.annotation.Nullable
  private List<MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner> tenantQuotas;

  public static final String SERIALIZED_NAME_TIME_ZONE = "timeZone";
  @SerializedName(SERIALIZED_NAME_TIME_ZONE)
  @javax.annotation.Nullable
  private String timeZone;

  public MailPatchCampaignsByCampaignIdRequestPolicy() {
  }

  public MailPatchCampaignsByCampaignIdRequestPolicy domainQuotas(@javax.annotation.Nullable List<MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner> domainQuotas) {
    this.domainQuotas = domainQuotas;
    this.reaconPresentFields.add(SERIALIZED_NAME_DOMAIN_QUOTAS);
    return this;
  }

  public MailPatchCampaignsByCampaignIdRequestPolicy addDomainQuotasItem(MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner domainQuotasItem) {
    if (this.domainQuotas == null) {
      this.domainQuotas = new ArrayList<>();
    }
    this.domainQuotas.add(domainQuotasItem);
    return this;
  }

  /**
   * Get domainQuotas
   * @return domainQuotas
   */
  @javax.annotation.Nullable
  public List<MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner> getDomainQuotas() {
    return domainQuotas;
  }

  public void setDomainQuotas(@javax.annotation.Nullable List<MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner> domainQuotas) {
    this.domainQuotas = domainQuotas;
    this.reaconPresentFields.add(SERIALIZED_NAME_DOMAIN_QUOTAS);
  }


  public MailPatchCampaignsByCampaignIdRequestPolicy mailboxQuotas(@javax.annotation.Nullable List<MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner> mailboxQuotas) {
    this.mailboxQuotas = mailboxQuotas;
    this.reaconPresentFields.add(SERIALIZED_NAME_MAILBOX_QUOTAS);
    return this;
  }

  public MailPatchCampaignsByCampaignIdRequestPolicy addMailboxQuotasItem(MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner mailboxQuotasItem) {
    if (this.mailboxQuotas == null) {
      this.mailboxQuotas = new ArrayList<>();
    }
    this.mailboxQuotas.add(mailboxQuotasItem);
    return this;
  }

  /**
   * Get mailboxQuotas
   * @return mailboxQuotas
   */
  @javax.annotation.Nullable
  public List<MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner> getMailboxQuotas() {
    return mailboxQuotas;
  }

  public void setMailboxQuotas(@javax.annotation.Nullable List<MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner> mailboxQuotas) {
    this.mailboxQuotas = mailboxQuotas;
    this.reaconPresentFields.add(SERIALIZED_NAME_MAILBOX_QUOTAS);
  }


  public MailPatchCampaignsByCampaignIdRequestPolicy recipientCooldownMs(@javax.annotation.Nullable Integer recipientCooldownMs) {
    this.recipientCooldownMs = recipientCooldownMs;
    this.reaconPresentFields.add(SERIALIZED_NAME_RECIPIENT_COOLDOWN_MS);
    return this;
  }

  /**
   * Get recipientCooldownMs
   * minimum: 0
   * maximum: 31536000000
   * @return recipientCooldownMs
   */
  @javax.annotation.Nullable
  public Integer getRecipientCooldownMs() {
    return recipientCooldownMs;
  }

  public void setRecipientCooldownMs(@javax.annotation.Nullable Integer recipientCooldownMs) {
    this.recipientCooldownMs = recipientCooldownMs;
    this.reaconPresentFields.add(SERIALIZED_NAME_RECIPIENT_COOLDOWN_MS);
  }


  public MailPatchCampaignsByCampaignIdRequestPolicy recipientQuotas(@javax.annotation.Nullable List<MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner> recipientQuotas) {
    this.recipientQuotas = recipientQuotas;
    this.reaconPresentFields.add(SERIALIZED_NAME_RECIPIENT_QUOTAS);
    return this;
  }

  public MailPatchCampaignsByCampaignIdRequestPolicy addRecipientQuotasItem(MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner recipientQuotasItem) {
    if (this.recipientQuotas == null) {
      this.recipientQuotas = new ArrayList<>();
    }
    this.recipientQuotas.add(recipientQuotasItem);
    return this;
  }

  /**
   * Get recipientQuotas
   * @return recipientQuotas
   */
  @javax.annotation.Nullable
  public List<MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner> getRecipientQuotas() {
    return recipientQuotas;
  }

  public void setRecipientQuotas(@javax.annotation.Nullable List<MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner> recipientQuotas) {
    this.recipientQuotas = recipientQuotas;
    this.reaconPresentFields.add(SERIALIZED_NAME_RECIPIENT_QUOTAS);
  }


  public MailPatchCampaignsByCampaignIdRequestPolicy sendingWindows(@javax.annotation.Nullable List<MailPatchCampaignsByCampaignIdRequestPolicySendingWindowsInner> sendingWindows) {
    this.sendingWindows = sendingWindows;
    this.reaconPresentFields.add(SERIALIZED_NAME_SENDING_WINDOWS);
    return this;
  }

  public MailPatchCampaignsByCampaignIdRequestPolicy addSendingWindowsItem(MailPatchCampaignsByCampaignIdRequestPolicySendingWindowsInner sendingWindowsItem) {
    if (this.sendingWindows == null) {
      this.sendingWindows = new ArrayList<>();
    }
    this.sendingWindows.add(sendingWindowsItem);
    return this;
  }

  /**
   * Get sendingWindows
   * @return sendingWindows
   */
  @javax.annotation.Nullable
  public List<MailPatchCampaignsByCampaignIdRequestPolicySendingWindowsInner> getSendingWindows() {
    return sendingWindows;
  }

  public void setSendingWindows(@javax.annotation.Nullable List<MailPatchCampaignsByCampaignIdRequestPolicySendingWindowsInner> sendingWindows) {
    this.sendingWindows = sendingWindows;
    this.reaconPresentFields.add(SERIALIZED_NAME_SENDING_WINDOWS);
  }


  public MailPatchCampaignsByCampaignIdRequestPolicy tenantQuotas(@javax.annotation.Nullable List<MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner> tenantQuotas) {
    this.tenantQuotas = tenantQuotas;
    this.reaconPresentFields.add(SERIALIZED_NAME_TENANT_QUOTAS);
    return this;
  }

  public MailPatchCampaignsByCampaignIdRequestPolicy addTenantQuotasItem(MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner tenantQuotasItem) {
    if (this.tenantQuotas == null) {
      this.tenantQuotas = new ArrayList<>();
    }
    this.tenantQuotas.add(tenantQuotasItem);
    return this;
  }

  /**
   * Get tenantQuotas
   * @return tenantQuotas
   */
  @javax.annotation.Nullable
  public List<MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner> getTenantQuotas() {
    return tenantQuotas;
  }

  public void setTenantQuotas(@javax.annotation.Nullable List<MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner> tenantQuotas) {
    this.tenantQuotas = tenantQuotas;
    this.reaconPresentFields.add(SERIALIZED_NAME_TENANT_QUOTAS);
  }


  public MailPatchCampaignsByCampaignIdRequestPolicy timeZone(@javax.annotation.Nullable String timeZone) {
    this.timeZone = timeZone;
    this.reaconPresentFields.add(SERIALIZED_NAME_TIME_ZONE);
    return this;
  }

  /**
   * Get timeZone
   * @return timeZone
   */
  @javax.annotation.Nullable
  public String getTimeZone() {
    return timeZone;
  }

  public void setTimeZone(@javax.annotation.Nullable String timeZone) {
    this.timeZone = timeZone;
    this.reaconPresentFields.add(SERIALIZED_NAME_TIME_ZONE);
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MailPatchCampaignsByCampaignIdRequestPolicy mailPatchCampaignsByCampaignIdRequestPolicy = (MailPatchCampaignsByCampaignIdRequestPolicy) o;
    return Objects.equals(this.domainQuotas, mailPatchCampaignsByCampaignIdRequestPolicy.domainQuotas) &&
        Objects.equals(this.mailboxQuotas, mailPatchCampaignsByCampaignIdRequestPolicy.mailboxQuotas) &&
        Objects.equals(this.recipientCooldownMs, mailPatchCampaignsByCampaignIdRequestPolicy.recipientCooldownMs) &&
        Objects.equals(this.recipientQuotas, mailPatchCampaignsByCampaignIdRequestPolicy.recipientQuotas) &&
        Objects.equals(this.sendingWindows, mailPatchCampaignsByCampaignIdRequestPolicy.sendingWindows) &&
        Objects.equals(this.tenantQuotas, mailPatchCampaignsByCampaignIdRequestPolicy.tenantQuotas) &&
        Objects.equals(this.timeZone, mailPatchCampaignsByCampaignIdRequestPolicy.timeZone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(domainQuotas, mailboxQuotas, recipientCooldownMs, recipientQuotas, sendingWindows, tenantQuotas, timeZone);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MailPatchCampaignsByCampaignIdRequestPolicy {\n");
    sb.append("    domainQuotas: ").append(toIndentedString(domainQuotas)).append("\n");
    sb.append("    mailboxQuotas: ").append(toIndentedString(mailboxQuotas)).append("\n");
    sb.append("    recipientCooldownMs: ").append(toIndentedString(recipientCooldownMs)).append("\n");
    sb.append("    recipientQuotas: ").append(toIndentedString(recipientQuotas)).append("\n");
    sb.append("    sendingWindows: ").append(toIndentedString(sendingWindows)).append("\n");
    sb.append("    tenantQuotas: ").append(toIndentedString(tenantQuotas)).append("\n");
    sb.append("    timeZone: ").append(toIndentedString(timeZone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("domainQuotas", "mailboxQuotas", "recipientCooldownMs", "recipientQuotas", "sendingWindows", "tenantQuotas", "timeZone"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MailPatchCampaignsByCampaignIdRequestPolicy
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MailPatchCampaignsByCampaignIdRequestPolicy.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in MailPatchCampaignsByCampaignIdRequestPolicy is not found in the empty JSON string", MailPatchCampaignsByCampaignIdRequestPolicy.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MailPatchCampaignsByCampaignIdRequestPolicy.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `MailPatchCampaignsByCampaignIdRequestPolicy` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("domainQuotas") != null && !jsonObj.get("domainQuotas").isJsonNull()) {
        JsonArray jsonArraydomainQuotas = jsonObj.getAsJsonArray("domainQuotas");
        if (jsonArraydomainQuotas != null) {
          // ensure the json data is an array
          if (!jsonObj.get("domainQuotas").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `domainQuotas` to be an array in the JSON string but got `%s`", jsonObj.get("domainQuotas").toString()));
          }

          // validate the optional field `domainQuotas` (array)
          for (int i = 0; i < jsonArraydomainQuotas.size(); i++) {
            MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner.validateJsonElement(jsonArraydomainQuotas.get(i));
          };
        }
      }
      if (jsonObj.get("mailboxQuotas") != null && !jsonObj.get("mailboxQuotas").isJsonNull()) {
        JsonArray jsonArraymailboxQuotas = jsonObj.getAsJsonArray("mailboxQuotas");
        if (jsonArraymailboxQuotas != null) {
          // ensure the json data is an array
          if (!jsonObj.get("mailboxQuotas").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `mailboxQuotas` to be an array in the JSON string but got `%s`", jsonObj.get("mailboxQuotas").toString()));
          }

          // validate the optional field `mailboxQuotas` (array)
          for (int i = 0; i < jsonArraymailboxQuotas.size(); i++) {
            MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner.validateJsonElement(jsonArraymailboxQuotas.get(i));
          };
        }
      }
      if (jsonObj.get("recipientQuotas") != null && !jsonObj.get("recipientQuotas").isJsonNull()) {
        JsonArray jsonArrayrecipientQuotas = jsonObj.getAsJsonArray("recipientQuotas");
        if (jsonArrayrecipientQuotas != null) {
          // ensure the json data is an array
          if (!jsonObj.get("recipientQuotas").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `recipientQuotas` to be an array in the JSON string but got `%s`", jsonObj.get("recipientQuotas").toString()));
          }

          // validate the optional field `recipientQuotas` (array)
          for (int i = 0; i < jsonArrayrecipientQuotas.size(); i++) {
            MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner.validateJsonElement(jsonArrayrecipientQuotas.get(i));
          };
        }
      }
      if (jsonObj.get("sendingWindows") != null && !jsonObj.get("sendingWindows").isJsonNull()) {
        JsonArray jsonArraysendingWindows = jsonObj.getAsJsonArray("sendingWindows");
        if (jsonArraysendingWindows != null) {
          // ensure the json data is an array
          if (!jsonObj.get("sendingWindows").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `sendingWindows` to be an array in the JSON string but got `%s`", jsonObj.get("sendingWindows").toString()));
          }

          // validate the optional field `sendingWindows` (array)
          for (int i = 0; i < jsonArraysendingWindows.size(); i++) {
            MailPatchCampaignsByCampaignIdRequestPolicySendingWindowsInner.validateJsonElement(jsonArraysendingWindows.get(i));
          };
        }
      }
      if (jsonObj.get("tenantQuotas") != null && !jsonObj.get("tenantQuotas").isJsonNull()) {
        JsonArray jsonArraytenantQuotas = jsonObj.getAsJsonArray("tenantQuotas");
        if (jsonArraytenantQuotas != null) {
          // ensure the json data is an array
          if (!jsonObj.get("tenantQuotas").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `tenantQuotas` to be an array in the JSON string but got `%s`", jsonObj.get("tenantQuotas").toString()));
          }

          // validate the optional field `tenantQuotas` (array)
          for (int i = 0; i < jsonArraytenantQuotas.size(); i++) {
            MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner.validateJsonElement(jsonArraytenantQuotas.get(i));
          };
        }
      }
      if ((jsonObj.get("timeZone") != null && !jsonObj.get("timeZone").isJsonNull()) && !jsonObj.get("timeZone").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `timeZone` to be a primitive type in the JSON string but got `%s`", jsonObj.get("timeZone").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MailPatchCampaignsByCampaignIdRequestPolicy.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MailPatchCampaignsByCampaignIdRequestPolicy' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MailPatchCampaignsByCampaignIdRequestPolicy> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MailPatchCampaignsByCampaignIdRequestPolicy.class));

       return (TypeAdapter<T>) new TypeAdapter<MailPatchCampaignsByCampaignIdRequestPolicy>() {
           @Override
           public void write(JsonWriter out, MailPatchCampaignsByCampaignIdRequestPolicy value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             if (value.domainQuotas == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_DOMAIN_QUOTAS)) obj.add(SERIALIZED_NAME_DOMAIN_QUOTAS, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_DOMAIN_QUOTAS);
             }
             if (value.mailboxQuotas == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_MAILBOX_QUOTAS)) obj.add(SERIALIZED_NAME_MAILBOX_QUOTAS, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_MAILBOX_QUOTAS);
             }
             if (value.recipientCooldownMs == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_RECIPIENT_COOLDOWN_MS)) obj.add(SERIALIZED_NAME_RECIPIENT_COOLDOWN_MS, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_RECIPIENT_COOLDOWN_MS);
             }
             if (value.recipientQuotas == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_RECIPIENT_QUOTAS)) obj.add(SERIALIZED_NAME_RECIPIENT_QUOTAS, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_RECIPIENT_QUOTAS);
             }
             if (value.sendingWindows == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_SENDING_WINDOWS)) obj.add(SERIALIZED_NAME_SENDING_WINDOWS, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_SENDING_WINDOWS);
             }
             if (value.tenantQuotas == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_TENANT_QUOTAS)) obj.add(SERIALIZED_NAME_TENANT_QUOTAS, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_TENANT_QUOTAS);
             }
             if (value.timeZone == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_TIME_ZONE)) obj.add(SERIALIZED_NAME_TIME_ZONE, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_TIME_ZONE);
             }
             boolean previousSerializeNulls = out.getSerializeNulls();
             out.setSerializeNulls(true);
             try { elementAdapter.write(out, obj); }
             finally { out.setSerializeNulls(previousSerializeNulls); }
           }

           @Override
           public MailPatchCampaignsByCampaignIdRequestPolicy read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             MailPatchCampaignsByCampaignIdRequestPolicy instance = thisAdapter.fromJsonTree(jsonElement);
             instance.reaconPresentFields.addAll(jsonElement.getAsJsonObject().keySet());
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MailPatchCampaignsByCampaignIdRequestPolicy given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MailPatchCampaignsByCampaignIdRequestPolicy
   * @throws IOException if the JSON string is invalid with respect to MailPatchCampaignsByCampaignIdRequestPolicy
   */
  public static MailPatchCampaignsByCampaignIdRequestPolicy fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MailPatchCampaignsByCampaignIdRequestPolicy.class);
  }

  /**
   * Convert an instance of MailPatchCampaignsByCampaignIdRequestPolicy to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

