/*
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.reacon.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.reacon.sdk.JSON;

/**
 * MailPostCrmContactsBatchRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class MailPostCrmContactsBatchRequest {
  private transient java.util.Set<String> reaconPresentFields = new java.util.HashSet<>();

  /** Whether a wire property was supplied, including an explicit null. */
  public boolean isFieldSet(String wireName) {
    switch (wireName) {
      case SERIALIZED_NAME_CONTACT_IDS: return reaconPresentFields.contains(SERIALIZED_NAME_CONTACT_IDS) || this.contactIds != null;
      default: throw new IllegalArgumentException("Unknown wire property: " + wireName);
    }
  }

  /** Omit an optional property again; required properties cannot be unset. */
  public void unsetField(String wireName) {
    if (openapiRequiredFields.contains(wireName)) throw new IllegalArgumentException("Required wire property: " + wireName);
    switch (wireName) {
      case SERIALIZED_NAME_CONTACT_IDS: this.contactIds = null; break;
      default: throw new IllegalArgumentException("Unknown wire property: " + wireName);
    }
    reaconPresentFields.remove(wireName);
  }

  public static final String SERIALIZED_NAME_CONTACT_IDS = "contactIds";
  @SerializedName(SERIALIZED_NAME_CONTACT_IDS)
  @javax.annotation.Nonnull
  private List<UUID> contactIds = new ArrayList<>();

  public MailPostCrmContactsBatchRequest() {
  }

  public MailPostCrmContactsBatchRequest contactIds(@javax.annotation.Nonnull List<UUID> contactIds) {
    this.contactIds = contactIds;
    this.reaconPresentFields.add(SERIALIZED_NAME_CONTACT_IDS);
    return this;
  }

  public MailPostCrmContactsBatchRequest addContactIdsItem(UUID contactIdsItem) {
    if (this.contactIds == null) {
      this.contactIds = new ArrayList<>();
    }
    this.contactIds.add(contactIdsItem);
    return this;
  }

  /**
   * Get contactIds
   * @return contactIds
   */
  @javax.annotation.Nonnull
  public List<UUID> getContactIds() {
    return contactIds;
  }

  public void setContactIds(@javax.annotation.Nonnull List<UUID> contactIds) {
    this.contactIds = contactIds;
    this.reaconPresentFields.add(SERIALIZED_NAME_CONTACT_IDS);
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MailPostCrmContactsBatchRequest mailPostCrmContactsBatchRequest = (MailPostCrmContactsBatchRequest) o;
    return Objects.equals(this.contactIds, mailPostCrmContactsBatchRequest.contactIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contactIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MailPostCrmContactsBatchRequest {\n");
    sb.append("    contactIds: ").append(toIndentedString(contactIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("contactIds"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("contactIds"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MailPostCrmContactsBatchRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MailPostCrmContactsBatchRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in MailPostCrmContactsBatchRequest is not found in the empty JSON string", MailPostCrmContactsBatchRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MailPostCrmContactsBatchRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `MailPostCrmContactsBatchRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : MailPostCrmContactsBatchRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the required json array is present
      if (jsonObj.get("contactIds") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("contactIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `contactIds` to be an array in the JSON string but got `%s`", jsonObj.get("contactIds").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MailPostCrmContactsBatchRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MailPostCrmContactsBatchRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MailPostCrmContactsBatchRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MailPostCrmContactsBatchRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<MailPostCrmContactsBatchRequest>() {
           @Override
           public void write(JsonWriter out, MailPostCrmContactsBatchRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             if (value.contactIds == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_CONTACT_IDS)) obj.add(SERIALIZED_NAME_CONTACT_IDS, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_CONTACT_IDS);
             }
             boolean previousSerializeNulls = out.getSerializeNulls();
             out.setSerializeNulls(true);
             try { elementAdapter.write(out, obj); }
             finally { out.setSerializeNulls(previousSerializeNulls); }
           }

           @Override
           public MailPostCrmContactsBatchRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             MailPostCrmContactsBatchRequest instance = thisAdapter.fromJsonTree(jsonElement);
             instance.reaconPresentFields.addAll(jsonElement.getAsJsonObject().keySet());
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MailPostCrmContactsBatchRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MailPostCrmContactsBatchRequest
   * @throws IOException if the JSON string is invalid with respect to MailPostCrmContactsBatchRequest
   */
  public static MailPostCrmContactsBatchRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MailPostCrmContactsBatchRequest.class);
  }

  /**
   * Convert an instance of MailPostCrmContactsBatchRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

