/*
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.reacon.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.reacon.sdk.model.MailConversationThread;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.reacon.sdk.JSON;

/**
 * MailGetInboxThreadsResponse200
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class MailGetInboxThreadsResponse200 {
  private transient java.util.Set<String> reaconPresentFields = new java.util.HashSet<>();

  /** Whether a wire property was supplied, including an explicit null. */
  public boolean isFieldSet(String wireName) {
    switch (wireName) {
      case SERIALIZED_NAME_SAMPLE_LIMITED: return reaconPresentFields.contains(SERIALIZED_NAME_SAMPLE_LIMITED) || this.sampleLimited != null;
      case SERIALIZED_NAME_THREADS: return reaconPresentFields.contains(SERIALIZED_NAME_THREADS) || this.threads != null;
      default: throw new IllegalArgumentException("Unknown wire property: " + wireName);
    }
  }

  /** Omit an optional property again; required properties cannot be unset. */
  public void unsetField(String wireName) {
    if (openapiRequiredFields.contains(wireName)) throw new IllegalArgumentException("Required wire property: " + wireName);
    switch (wireName) {
      case SERIALIZED_NAME_SAMPLE_LIMITED: this.sampleLimited = null; break;
      case SERIALIZED_NAME_THREADS: this.threads = null; break;
      default: throw new IllegalArgumentException("Unknown wire property: " + wireName);
    }
    reaconPresentFields.remove(wireName);
  }

  public static final String SERIALIZED_NAME_SAMPLE_LIMITED = "sampleLimited";
  @SerializedName(SERIALIZED_NAME_SAMPLE_LIMITED)
  @javax.annotation.Nonnull
  private Boolean sampleLimited;

  public static final String SERIALIZED_NAME_THREADS = "threads";
  @SerializedName(SERIALIZED_NAME_THREADS)
  @javax.annotation.Nonnull
  private List<MailConversationThread> threads = new ArrayList<>();

  public MailGetInboxThreadsResponse200() {
  }

  public MailGetInboxThreadsResponse200 sampleLimited(@javax.annotation.Nonnull Boolean sampleLimited) {
    this.sampleLimited = sampleLimited;
    this.reaconPresentFields.add(SERIALIZED_NAME_SAMPLE_LIMITED);
    return this;
  }

  /**
   * Get sampleLimited
   * @return sampleLimited
   */
  @javax.annotation.Nonnull
  public Boolean getSampleLimited() {
    return sampleLimited;
  }

  public void setSampleLimited(@javax.annotation.Nonnull Boolean sampleLimited) {
    this.sampleLimited = sampleLimited;
    this.reaconPresentFields.add(SERIALIZED_NAME_SAMPLE_LIMITED);
  }


  public MailGetInboxThreadsResponse200 threads(@javax.annotation.Nonnull List<MailConversationThread> threads) {
    this.threads = threads;
    this.reaconPresentFields.add(SERIALIZED_NAME_THREADS);
    return this;
  }

  public MailGetInboxThreadsResponse200 addThreadsItem(MailConversationThread threadsItem) {
    if (this.threads == null) {
      this.threads = new ArrayList<>();
    }
    this.threads.add(threadsItem);
    return this;
  }

  /**
   * Get threads
   * @return threads
   */
  @javax.annotation.Nonnull
  public List<MailConversationThread> getThreads() {
    return threads;
  }

  public void setThreads(@javax.annotation.Nonnull List<MailConversationThread> threads) {
    this.threads = threads;
    this.reaconPresentFields.add(SERIALIZED_NAME_THREADS);
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the MailGetInboxThreadsResponse200 instance itself
   */
  public MailGetInboxThreadsResponse200 putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MailGetInboxThreadsResponse200 mailGetInboxThreadsResponse200 = (MailGetInboxThreadsResponse200) o;
    return Objects.equals(this.sampleLimited, mailGetInboxThreadsResponse200.sampleLimited) &&
        Objects.equals(this.threads, mailGetInboxThreadsResponse200.threads)&&
        Objects.equals(this.additionalProperties, mailGetInboxThreadsResponse200.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sampleLimited, threads, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MailGetInboxThreadsResponse200 {\n");
    sb.append("    sampleLimited: ").append(toIndentedString(sampleLimited)).append("\n");
    sb.append("    threads: ").append(toIndentedString(threads)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("sampleLimited", "threads"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("sampleLimited", "threads"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MailGetInboxThreadsResponse200
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MailGetInboxThreadsResponse200.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in MailGetInboxThreadsResponse200 is not found in the empty JSON string", MailGetInboxThreadsResponse200.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : MailGetInboxThreadsResponse200.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("threads") != null) {
        if (!jsonObj.get("threads").isJsonArray()) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `threads` to be an array in the JSON string but got `%s`", jsonObj.get("threads").toString()));
        }
        JsonArray jsonArraythreads = jsonObj.getAsJsonArray("threads");
        // validate the required field `threads` (array)
        for (int i = 0; i < jsonArraythreads.size(); i++) {
          MailConversationThread.validateJsonElement(jsonArraythreads.get(i));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MailGetInboxThreadsResponse200.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MailGetInboxThreadsResponse200' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MailGetInboxThreadsResponse200> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MailGetInboxThreadsResponse200.class));

       return (TypeAdapter<T>) new TypeAdapter<MailGetInboxThreadsResponse200>() {
           @Override
           public void write(JsonWriter out, MailGetInboxThreadsResponse200 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             if (value.sampleLimited == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_SAMPLE_LIMITED)) obj.add(SERIALIZED_NAME_SAMPLE_LIMITED, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_SAMPLE_LIMITED);
             }
             if (value.threads == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_THREADS)) obj.add(SERIALIZED_NAME_THREADS, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_THREADS);
             }
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonNull()) {
                     obj.add(entry.getKey(), JsonNull.INSTANCE);
                   } else if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             boolean previousSerializeNulls = out.getSerializeNulls();
             out.setSerializeNulls(true);
             try { elementAdapter.write(out, obj); }
             finally { out.setSerializeNulls(previousSerializeNulls); }
           }

           @Override
           public MailGetInboxThreadsResponse200 read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             MailGetInboxThreadsResponse200 instance = thisAdapter.fromJsonTree(jsonObj);
             instance.reaconPresentFields.addAll(jsonObj.keySet());
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MailGetInboxThreadsResponse200 given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MailGetInboxThreadsResponse200
   * @throws IOException if the JSON string is invalid with respect to MailGetInboxThreadsResponse200
   */
  public static MailGetInboxThreadsResponse200 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MailGetInboxThreadsResponse200.class);
  }

  /**
   * Convert an instance of MailGetInboxThreadsResponse200 to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

