/*
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.reacon.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.reacon.sdk.model.MailPostReplyAutomationsRequestActions;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.reacon.sdk.JSON;

/**
 * MailPostReplyAutomationsRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class MailPostReplyAutomationsRequest {
  private transient java.util.Set<String> reaconPresentFields = new java.util.HashSet<>();

  /** Whether a wire property was supplied, including an explicit null. */
  public boolean isFieldSet(String wireName) {
    switch (wireName) {
      case SERIALIZED_NAME_ACTIONS: return reaconPresentFields.contains(SERIALIZED_NAME_ACTIONS) || this.actions != null;
      case SERIALIZED_NAME_ENABLED: return reaconPresentFields.contains(SERIALIZED_NAME_ENABLED) || this.enabled != null;
      case SERIALIZED_NAME_ID: return reaconPresentFields.contains(SERIALIZED_NAME_ID) || this.id != null;
      case SERIALIZED_NAME_LABELS: return reaconPresentFields.contains(SERIALIZED_NAME_LABELS) || this.labels != null;
      case SERIALIZED_NAME_NAME: return reaconPresentFields.contains(SERIALIZED_NAME_NAME) || this.name != null;
      case SERIALIZED_NAME_PRIORITY: return reaconPresentFields.contains(SERIALIZED_NAME_PRIORITY) || this.priority != null;
      default: throw new IllegalArgumentException("Unknown wire property: " + wireName);
    }
  }

  /** Omit an optional property again; required properties cannot be unset. */
  public void unsetField(String wireName) {
    if (openapiRequiredFields.contains(wireName)) throw new IllegalArgumentException("Required wire property: " + wireName);
    switch (wireName) {
      case SERIALIZED_NAME_ACTIONS: this.actions = null; break;
      case SERIALIZED_NAME_ENABLED: this.enabled = null; break;
      case SERIALIZED_NAME_ID: this.id = null; break;
      case SERIALIZED_NAME_LABELS: this.labels = null; break;
      case SERIALIZED_NAME_NAME: this.name = null; break;
      case SERIALIZED_NAME_PRIORITY: this.priority = null; break;
      default: throw new IllegalArgumentException("Unknown wire property: " + wireName);
    }
    reaconPresentFields.remove(wireName);
  }

  public static final String SERIALIZED_NAME_ACTIONS = "actions";
  @SerializedName(SERIALIZED_NAME_ACTIONS)
  @javax.annotation.Nonnull
  private MailPostReplyAutomationsRequestActions actions;

  public static final String SERIALIZED_NAME_ENABLED = "enabled";
  @SerializedName(SERIALIZED_NAME_ENABLED)
  @javax.annotation.Nullable
  private Boolean enabled;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  /**
   * Gets or Sets labels
   */
  @JsonAdapter(LabelsEnum.Adapter.class)
  public enum LabelsEnum {
    INTERESTED("interested"),
    
    NOT_INTERESTED("not_interested"),
    
    OUT_OF_OFFICE("out_of_office"),
    
    WRONG_PERSON("wrong_person"),
    
    MEETING_BOOKED("meeting_booked"),
    
    UNSUBSCRIBE("unsubscribe"),
    
    BOUNCE("bounce"),
    
    UNKNOWN("unknown");

    private String value;

    LabelsEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static LabelsEnum fromValue(String value) {
      for (LabelsEnum b : LabelsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<LabelsEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final LabelsEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public LabelsEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return LabelsEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      LabelsEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_LABELS = "labels";
  @SerializedName(SERIALIZED_NAME_LABELS)
  @javax.annotation.Nonnull
  private List<LabelsEnum> labels = new ArrayList<>();

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_PRIORITY = "priority";
  @SerializedName(SERIALIZED_NAME_PRIORITY)
  @javax.annotation.Nullable
  private Integer priority;

  public MailPostReplyAutomationsRequest() {
  }

  public MailPostReplyAutomationsRequest actions(@javax.annotation.Nonnull MailPostReplyAutomationsRequestActions actions) {
    this.actions = actions;
    this.reaconPresentFields.add(SERIALIZED_NAME_ACTIONS);
    return this;
  }

  /**
   * Get actions
   * @return actions
   */
  @javax.annotation.Nonnull
  public MailPostReplyAutomationsRequestActions getActions() {
    return actions;
  }

  public void setActions(@javax.annotation.Nonnull MailPostReplyAutomationsRequestActions actions) {
    this.actions = actions;
    this.reaconPresentFields.add(SERIALIZED_NAME_ACTIONS);
  }


  public MailPostReplyAutomationsRequest enabled(@javax.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
    this.reaconPresentFields.add(SERIALIZED_NAME_ENABLED);
    return this;
  }

  /**
   * Get enabled
   * @return enabled
   */
  @javax.annotation.Nullable
  public Boolean getEnabled() {
    return enabled;
  }

  public void setEnabled(@javax.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
    this.reaconPresentFields.add(SERIALIZED_NAME_ENABLED);
  }


  public MailPostReplyAutomationsRequest id(@javax.annotation.Nullable String id) {
    this.id = id;
    this.reaconPresentFields.add(SERIALIZED_NAME_ID);
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
    this.reaconPresentFields.add(SERIALIZED_NAME_ID);
  }


  public MailPostReplyAutomationsRequest labels(@javax.annotation.Nonnull List<LabelsEnum> labels) {
    this.labels = labels;
    this.reaconPresentFields.add(SERIALIZED_NAME_LABELS);
    return this;
  }

  public MailPostReplyAutomationsRequest addLabelsItem(LabelsEnum labelsItem) {
    if (this.labels == null) {
      this.labels = new ArrayList<>();
    }
    this.labels.add(labelsItem);
    return this;
  }

  /**
   * Get labels
   * @return labels
   */
  @javax.annotation.Nonnull
  public List<LabelsEnum> getLabels() {
    return labels;
  }

  public void setLabels(@javax.annotation.Nonnull List<LabelsEnum> labels) {
    this.labels = labels;
    this.reaconPresentFields.add(SERIALIZED_NAME_LABELS);
  }


  public MailPostReplyAutomationsRequest name(@javax.annotation.Nonnull String name) {
    this.name = name;
    this.reaconPresentFields.add(SERIALIZED_NAME_NAME);
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
    this.reaconPresentFields.add(SERIALIZED_NAME_NAME);
  }


  public MailPostReplyAutomationsRequest priority(@javax.annotation.Nullable Integer priority) {
    this.priority = priority;
    this.reaconPresentFields.add(SERIALIZED_NAME_PRIORITY);
    return this;
  }

  /**
   * Get priority
   * minimum: 0
   * maximum: 100000
   * @return priority
   */
  @javax.annotation.Nullable
  public Integer getPriority() {
    return priority;
  }

  public void setPriority(@javax.annotation.Nullable Integer priority) {
    this.priority = priority;
    this.reaconPresentFields.add(SERIALIZED_NAME_PRIORITY);
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MailPostReplyAutomationsRequest mailPostReplyAutomationsRequest = (MailPostReplyAutomationsRequest) o;
    return Objects.equals(this.actions, mailPostReplyAutomationsRequest.actions) &&
        Objects.equals(this.enabled, mailPostReplyAutomationsRequest.enabled) &&
        Objects.equals(this.id, mailPostReplyAutomationsRequest.id) &&
        Objects.equals(this.labels, mailPostReplyAutomationsRequest.labels) &&
        Objects.equals(this.name, mailPostReplyAutomationsRequest.name) &&
        Objects.equals(this.priority, mailPostReplyAutomationsRequest.priority);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actions, enabled, id, labels, name, priority);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MailPostReplyAutomationsRequest {\n");
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("actions", "enabled", "id", "labels", "name", "priority"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("actions", "labels", "name"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MailPostReplyAutomationsRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MailPostReplyAutomationsRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in MailPostReplyAutomationsRequest is not found in the empty JSON string", MailPostReplyAutomationsRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MailPostReplyAutomationsRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `MailPostReplyAutomationsRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : MailPostReplyAutomationsRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `actions`
      MailPostReplyAutomationsRequestActions.validateJsonElement(jsonObj.get("actions"));
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("labels") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("labels").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `labels` to be an array in the JSON string but got `%s`", jsonObj.get("labels").toString()));
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MailPostReplyAutomationsRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MailPostReplyAutomationsRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MailPostReplyAutomationsRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MailPostReplyAutomationsRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<MailPostReplyAutomationsRequest>() {
           @Override
           public void write(JsonWriter out, MailPostReplyAutomationsRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             if (value.actions == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_ACTIONS)) obj.add(SERIALIZED_NAME_ACTIONS, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_ACTIONS);
             }
             if (value.enabled == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_ENABLED)) obj.add(SERIALIZED_NAME_ENABLED, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_ENABLED);
             }
             if (value.id == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_ID)) obj.add(SERIALIZED_NAME_ID, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_ID);
             }
             if (value.labels == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_LABELS)) obj.add(SERIALIZED_NAME_LABELS, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_LABELS);
             }
             if (value.name == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_NAME)) obj.add(SERIALIZED_NAME_NAME, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_NAME);
             }
             if (value.priority == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_PRIORITY)) obj.add(SERIALIZED_NAME_PRIORITY, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_PRIORITY);
             }
             boolean previousSerializeNulls = out.getSerializeNulls();
             out.setSerializeNulls(true);
             try { elementAdapter.write(out, obj); }
             finally { out.setSerializeNulls(previousSerializeNulls); }
           }

           @Override
           public MailPostReplyAutomationsRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             MailPostReplyAutomationsRequest instance = thisAdapter.fromJsonTree(jsonElement);
             instance.reaconPresentFields.addAll(jsonElement.getAsJsonObject().keySet());
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MailPostReplyAutomationsRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MailPostReplyAutomationsRequest
   * @throws IOException if the JSON string is invalid with respect to MailPostReplyAutomationsRequest
   */
  public static MailPostReplyAutomationsRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MailPostReplyAutomationsRequest.class);
  }

  /**
   * Convert an instance of MailPostReplyAutomationsRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

