/*
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.reacon.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.reacon.sdk.model.MailConversationEntryLastErrorAnyOf;
import io.reacon.sdk.model.MailConversationEntryLastErrorAnyOf1;
import io.reacon.sdk.model.MailConversationEntryLastErrorAnyOf2;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import io.reacon.sdk.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class MailConversationEntryLastError extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(MailConversationEntryLastError.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!MailConversationEntryLastError.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'MailConversationEntryLastError' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<MailConversationEntryLastErrorAnyOf> adapterMailConversationEntryLastErrorAnyOf = gson.getAdapter(TypeToken.get(MailConversationEntryLastErrorAnyOf.class));
            final TypeAdapter<MailConversationEntryLastErrorAnyOf1> adapterMailConversationEntryLastErrorAnyOf1 = gson.getAdapter(TypeToken.get(MailConversationEntryLastErrorAnyOf1.class));
            final TypeAdapter<MailConversationEntryLastErrorAnyOf2> adapterMailConversationEntryLastErrorAnyOf2 = gson.getAdapter(TypeToken.get(MailConversationEntryLastErrorAnyOf2.class));

            return (TypeAdapter<T>) new TypeAdapter<MailConversationEntryLastError>() {
                @Override
                public void write(JsonWriter out, MailConversationEntryLastError value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `MailConversationEntryLastErrorAnyOf`
                    if (value.getActualInstance() instanceof MailConversationEntryLastErrorAnyOf) {
                        JsonElement element = adapterMailConversationEntryLastErrorAnyOf.toJsonTree((MailConversationEntryLastErrorAnyOf)value.getActualInstance());
                        boolean previousSerializeNulls = out.getSerializeNulls();
                        out.setSerializeNulls(true);
                        try { elementAdapter.write(out, element); }
                        finally { out.setSerializeNulls(previousSerializeNulls); }
                        return;
                    }
                    // check if the actual instance is of the type `MailConversationEntryLastErrorAnyOf1`
                    if (value.getActualInstance() instanceof MailConversationEntryLastErrorAnyOf1) {
                        JsonElement element = adapterMailConversationEntryLastErrorAnyOf1.toJsonTree((MailConversationEntryLastErrorAnyOf1)value.getActualInstance());
                        boolean previousSerializeNulls = out.getSerializeNulls();
                        out.setSerializeNulls(true);
                        try { elementAdapter.write(out, element); }
                        finally { out.setSerializeNulls(previousSerializeNulls); }
                        return;
                    }
                    // check if the actual instance is of the type `MailConversationEntryLastErrorAnyOf2`
                    if (value.getActualInstance() instanceof MailConversationEntryLastErrorAnyOf2) {
                        JsonElement element = adapterMailConversationEntryLastErrorAnyOf2.toJsonTree((MailConversationEntryLastErrorAnyOf2)value.getActualInstance());
                        boolean previousSerializeNulls = out.getSerializeNulls();
                        out.setSerializeNulls(true);
                        try { elementAdapter.write(out, element); }
                        finally { out.setSerializeNulls(previousSerializeNulls); }
                        return;
                    }
                    throw new IOException("Failed to serialize as the type doesn't match anyOf schemas: MailConversationEntryLastErrorAnyOf, MailConversationEntryLastErrorAnyOf1, MailConversationEntryLastErrorAnyOf2");
                }

                @Override
                public MailConversationEntryLastError read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize MailConversationEntryLastErrorAnyOf
                    try {
                        // validate the JSON object to see if any exception is thrown
                        MailConversationEntryLastErrorAnyOf.validateJsonElement(jsonElement);
                        actualAdapter = adapterMailConversationEntryLastErrorAnyOf;
                        MailConversationEntryLastError ret = new MailConversationEntryLastError();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for MailConversationEntryLastErrorAnyOf failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'MailConversationEntryLastErrorAnyOf'", e);
                    }
                    // deserialize MailConversationEntryLastErrorAnyOf1
                    try {
                        // validate the JSON object to see if any exception is thrown
                        MailConversationEntryLastErrorAnyOf1.validateJsonElement(jsonElement);
                        actualAdapter = adapterMailConversationEntryLastErrorAnyOf1;
                        MailConversationEntryLastError ret = new MailConversationEntryLastError();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for MailConversationEntryLastErrorAnyOf1 failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'MailConversationEntryLastErrorAnyOf1'", e);
                    }
                    // deserialize MailConversationEntryLastErrorAnyOf2
                    try {
                        // validate the JSON object to see if any exception is thrown
                        MailConversationEntryLastErrorAnyOf2.validateJsonElement(jsonElement);
                        actualAdapter = adapterMailConversationEntryLastErrorAnyOf2;
                        MailConversationEntryLastError ret = new MailConversationEntryLastError();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for MailConversationEntryLastErrorAnyOf2 failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'MailConversationEntryLastErrorAnyOf2'", e);
                    }

                    throw new IOException(String.format(java.util.Locale.ROOT, "Failed deserialization for MailConversationEntryLastError: no class matches result, expected at least 1. Detailed failure message for anyOf schemas: %s. JSON: %s", errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in anyOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public MailConversationEntryLastError() {
        super("anyOf", Boolean.FALSE);
    }

    public MailConversationEntryLastError(Object o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("MailConversationEntryLastErrorAnyOf", MailConversationEntryLastErrorAnyOf.class);
        schemas.put("MailConversationEntryLastErrorAnyOf1", MailConversationEntryLastErrorAnyOf1.class);
        schemas.put("MailConversationEntryLastErrorAnyOf2", MailConversationEntryLastErrorAnyOf2.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return MailConversationEntryLastError.schemas;
    }

    /**
     * Set the instance that matches the anyOf child schema, check
     * the instance parameter is valid against the anyOf child schemas:
     * MailConversationEntryLastErrorAnyOf, MailConversationEntryLastErrorAnyOf1, MailConversationEntryLastErrorAnyOf2
     *
     * It could be an instance of the 'anyOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof MailConversationEntryLastErrorAnyOf) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof MailConversationEntryLastErrorAnyOf1) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof MailConversationEntryLastErrorAnyOf2) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be MailConversationEntryLastErrorAnyOf, MailConversationEntryLastErrorAnyOf1, MailConversationEntryLastErrorAnyOf2");
    }

    /**
     * Get the actual instance, which can be the following:
     * MailConversationEntryLastErrorAnyOf, MailConversationEntryLastErrorAnyOf1, MailConversationEntryLastErrorAnyOf2
     *
     * @return The actual instance (MailConversationEntryLastErrorAnyOf, MailConversationEntryLastErrorAnyOf1, MailConversationEntryLastErrorAnyOf2)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `MailConversationEntryLastErrorAnyOf`. If the actual instance is not `MailConversationEntryLastErrorAnyOf`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `MailConversationEntryLastErrorAnyOf`
     * @throws ClassCastException if the instance is not `MailConversationEntryLastErrorAnyOf`
     */
    public MailConversationEntryLastErrorAnyOf getMailConversationEntryLastErrorAnyOf() throws ClassCastException {
        return (MailConversationEntryLastErrorAnyOf)super.getActualInstance();
    }

    /**
     * Get the actual instance of `MailConversationEntryLastErrorAnyOf1`. If the actual instance is not `MailConversationEntryLastErrorAnyOf1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `MailConversationEntryLastErrorAnyOf1`
     * @throws ClassCastException if the instance is not `MailConversationEntryLastErrorAnyOf1`
     */
    public MailConversationEntryLastErrorAnyOf1 getMailConversationEntryLastErrorAnyOf1() throws ClassCastException {
        return (MailConversationEntryLastErrorAnyOf1)super.getActualInstance();
    }

    /**
     * Get the actual instance of `MailConversationEntryLastErrorAnyOf2`. If the actual instance is not `MailConversationEntryLastErrorAnyOf2`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `MailConversationEntryLastErrorAnyOf2`
     * @throws ClassCastException if the instance is not `MailConversationEntryLastErrorAnyOf2`
     */
    public MailConversationEntryLastErrorAnyOf2 getMailConversationEntryLastErrorAnyOf2() throws ClassCastException {
        return (MailConversationEntryLastErrorAnyOf2)super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to MailConversationEntryLastError
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate anyOf schemas one by one
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with MailConversationEntryLastErrorAnyOf
        try {
            MailConversationEntryLastErrorAnyOf.validateJsonElement(jsonElement);
            return;
        } catch (Exception e) {
            errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for MailConversationEntryLastErrorAnyOf failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with MailConversationEntryLastErrorAnyOf1
        try {
            MailConversationEntryLastErrorAnyOf1.validateJsonElement(jsonElement);
            return;
        } catch (Exception e) {
            errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for MailConversationEntryLastErrorAnyOf1 failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with MailConversationEntryLastErrorAnyOf2
        try {
            MailConversationEntryLastErrorAnyOf2.validateJsonElement(jsonElement);
            return;
        } catch (Exception e) {
            errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for MailConversationEntryLastErrorAnyOf2 failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        throw new IOException(String.format(java.util.Locale.ROOT, "The JSON string is invalid for MailConversationEntryLastError with anyOf schemas: MailConversationEntryLastErrorAnyOf, MailConversationEntryLastErrorAnyOf1, MailConversationEntryLastErrorAnyOf2. no class match the result, expected at least 1. Detailed failure message for anyOf schemas: %s. JSON: %s", errorMessages, jsonElement.toString()));
    }

    /**
     * Create an instance of MailConversationEntryLastError given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of MailConversationEntryLastError
     * @throws IOException if the JSON string is invalid with respect to MailConversationEntryLastError
     */
    public static MailConversationEntryLastError fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, MailConversationEntryLastError.class);
    }

    /**
     * Convert an instance of MailConversationEntryLastError to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

