/*
 * Reacon API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.reacon.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.reacon.sdk.model.SheetWorkflowValidation;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.reacon.sdk.JSON;

/**
 * SheetWorkflow
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class SheetWorkflow {
  private transient java.util.Set<String> reaconPresentFields = new java.util.HashSet<>();

  /** Whether a wire property was supplied, including an explicit null. */
  public boolean isFieldSet(String wireName) {
    switch (wireName) {
      case SERIALIZED_NAME_CAPABILITY: return reaconPresentFields.contains(SERIALIZED_NAME_CAPABILITY) || this.capability != null;
      case SERIALIZED_NAME_CONFIG: return reaconPresentFields.contains(SERIALIZED_NAME_CONFIG) || this.config != null;
      case SERIALIZED_NAME_CONNECTION_ID: return reaconPresentFields.contains(SERIALIZED_NAME_CONNECTION_ID) || this.connectionId != null;
      case SERIALIZED_NAME_CREATED_AT: return reaconPresentFields.contains(SERIALIZED_NAME_CREATED_AT) || this.createdAt != null;
      case SERIALIZED_NAME_ID: return reaconPresentFields.contains(SERIALIZED_NAME_ID) || this.id != null;
      case SERIALIZED_NAME_LABEL: return reaconPresentFields.contains(SERIALIZED_NAME_LABEL) || this.label != null;
      case SERIALIZED_NAME_REVISION: return reaconPresentFields.contains(SERIALIZED_NAME_REVISION) || this.revision != null;
      case SERIALIZED_NAME_STATE: return reaconPresentFields.contains(SERIALIZED_NAME_STATE) || this.state != null;
      case SERIALIZED_NAME_TEAM_ID: return reaconPresentFields.contains(SERIALIZED_NAME_TEAM_ID) || this.teamId != null;
      case SERIALIZED_NAME_UPDATED_AT: return reaconPresentFields.contains(SERIALIZED_NAME_UPDATED_AT) || this.updatedAt != null;
      case SERIALIZED_NAME_VALIDATION: return reaconPresentFields.contains(SERIALIZED_NAME_VALIDATION) || this.validation != null;
      default: throw new IllegalArgumentException("Unknown wire property: " + wireName);
    }
  }

  /** Omit an optional property again; required properties cannot be unset. */
  public void unsetField(String wireName) {
    if (openapiRequiredFields.contains(wireName)) throw new IllegalArgumentException("Required wire property: " + wireName);
    switch (wireName) {
      case SERIALIZED_NAME_CAPABILITY: this.capability = null; break;
      case SERIALIZED_NAME_CONFIG: this.config = null; break;
      case SERIALIZED_NAME_CONNECTION_ID: this.connectionId = null; break;
      case SERIALIZED_NAME_CREATED_AT: this.createdAt = null; break;
      case SERIALIZED_NAME_ID: this.id = null; break;
      case SERIALIZED_NAME_LABEL: this.label = null; break;
      case SERIALIZED_NAME_REVISION: this.revision = null; break;
      case SERIALIZED_NAME_STATE: this.state = null; break;
      case SERIALIZED_NAME_TEAM_ID: this.teamId = null; break;
      case SERIALIZED_NAME_UPDATED_AT: this.updatedAt = null; break;
      case SERIALIZED_NAME_VALIDATION: this.validation = null; break;
      default: throw new IllegalArgumentException("Unknown wire property: " + wireName);
    }
    reaconPresentFields.remove(wireName);
  }

  public static final String SERIALIZED_NAME_CAPABILITY = "capability";
  @SerializedName(SERIALIZED_NAME_CAPABILITY)
  @javax.annotation.Nonnull
  private String capability;

  public static final String SERIALIZED_NAME_CONFIG = "config";
  @SerializedName(SERIALIZED_NAME_CONFIG)
  @javax.annotation.Nonnull
  private Map<String, Object> config = new HashMap<>();

  public static final String SERIALIZED_NAME_CONNECTION_ID = "connectionId";
  @SerializedName(SERIALIZED_NAME_CONNECTION_ID)
  @javax.annotation.Nonnull
  private String connectionId;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nonnull
  private String createdAt;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_LABEL = "label";
  @SerializedName(SERIALIZED_NAME_LABEL)
  @javax.annotation.Nonnull
  private String label;

  public static final String SERIALIZED_NAME_REVISION = "revision";
  @SerializedName(SERIALIZED_NAME_REVISION)
  @javax.annotation.Nonnull
  private Integer revision;

  public static final String SERIALIZED_NAME_STATE = "state";
  @SerializedName(SERIALIZED_NAME_STATE)
  @javax.annotation.Nonnull
  private String state;

  public static final String SERIALIZED_NAME_TEAM_ID = "teamId";
  @SerializedName(SERIALIZED_NAME_TEAM_ID)
  @javax.annotation.Nonnull
  private String teamId;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nonnull
  private String updatedAt;

  public static final String SERIALIZED_NAME_VALIDATION = "validation";
  @SerializedName(SERIALIZED_NAME_VALIDATION)
  @javax.annotation.Nonnull
  private SheetWorkflowValidation validation;

  public SheetWorkflow() {
  }

  public SheetWorkflow capability(@javax.annotation.Nonnull String capability) {
    this.capability = capability;
    this.reaconPresentFields.add(SERIALIZED_NAME_CAPABILITY);
    return this;
  }

  /**
   * Known values: email.find, email.verify, domain.search. Clients preserve future values.
   * @return capability
   */
  @javax.annotation.Nonnull
  public String getCapability() {
    return capability;
  }

  public void setCapability(@javax.annotation.Nonnull String capability) {
    this.capability = capability;
    this.reaconPresentFields.add(SERIALIZED_NAME_CAPABILITY);
  }


  public SheetWorkflow config(@javax.annotation.Nonnull Map<String, Object> config) {
    this.config = config;
    this.reaconPresentFields.add(SERIALIZED_NAME_CONFIG);
    return this;
  }

  public SheetWorkflow putConfigItem(String key, Object configItem) {
    if (this.config == null) {
      this.config = new HashMap<>();
    }
    this.config.put(key, configItem);
    return this;
  }

  /**
   * Validated spreadsheet workflow configuration.
   * @return config
   */
  @javax.annotation.Nonnull
  public Map<String, Object> getConfig() {
    return config;
  }

  public void setConfig(@javax.annotation.Nonnull Map<String, Object> config) {
    this.config = config;
    this.reaconPresentFields.add(SERIALIZED_NAME_CONFIG);
  }


  public SheetWorkflow connectionId(@javax.annotation.Nonnull String connectionId) {
    this.connectionId = connectionId;
    this.reaconPresentFields.add(SERIALIZED_NAME_CONNECTION_ID);
    return this;
  }

  /**
   * Get connectionId
   * @return connectionId
   */
  @javax.annotation.Nonnull
  public String getConnectionId() {
    return connectionId;
  }

  public void setConnectionId(@javax.annotation.Nonnull String connectionId) {
    this.connectionId = connectionId;
    this.reaconPresentFields.add(SERIALIZED_NAME_CONNECTION_ID);
  }


  public SheetWorkflow createdAt(@javax.annotation.Nonnull String createdAt) {
    this.createdAt = createdAt;
    this.reaconPresentFields.add(SERIALIZED_NAME_CREATED_AT);
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nonnull
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nonnull String createdAt) {
    this.createdAt = createdAt;
    this.reaconPresentFields.add(SERIALIZED_NAME_CREATED_AT);
  }


  public SheetWorkflow id(@javax.annotation.Nonnull String id) {
    this.id = id;
    this.reaconPresentFields.add(SERIALIZED_NAME_ID);
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
    this.reaconPresentFields.add(SERIALIZED_NAME_ID);
  }


  public SheetWorkflow label(@javax.annotation.Nonnull String label) {
    this.label = label;
    this.reaconPresentFields.add(SERIALIZED_NAME_LABEL);
    return this;
  }

  /**
   * Get label
   * @return label
   */
  @javax.annotation.Nonnull
  public String getLabel() {
    return label;
  }

  public void setLabel(@javax.annotation.Nonnull String label) {
    this.label = label;
    this.reaconPresentFields.add(SERIALIZED_NAME_LABEL);
  }


  public SheetWorkflow revision(@javax.annotation.Nonnull Integer revision) {
    this.revision = revision;
    this.reaconPresentFields.add(SERIALIZED_NAME_REVISION);
    return this;
  }

  /**
   * Get revision
   * @return revision
   */
  @javax.annotation.Nonnull
  public Integer getRevision() {
    return revision;
  }

  public void setRevision(@javax.annotation.Nonnull Integer revision) {
    this.revision = revision;
    this.reaconPresentFields.add(SERIALIZED_NAME_REVISION);
  }


  public SheetWorkflow state(@javax.annotation.Nonnull String state) {
    this.state = state;
    this.reaconPresentFields.add(SERIALIZED_NAME_STATE);
    return this;
  }

  /**
   * Known values: active, paused. Clients preserve future values.
   * @return state
   */
  @javax.annotation.Nonnull
  public String getState() {
    return state;
  }

  public void setState(@javax.annotation.Nonnull String state) {
    this.state = state;
    this.reaconPresentFields.add(SERIALIZED_NAME_STATE);
  }


  public SheetWorkflow teamId(@javax.annotation.Nonnull String teamId) {
    this.teamId = teamId;
    this.reaconPresentFields.add(SERIALIZED_NAME_TEAM_ID);
    return this;
  }

  /**
   * Get teamId
   * @return teamId
   */
  @javax.annotation.Nonnull
  public String getTeamId() {
    return teamId;
  }

  public void setTeamId(@javax.annotation.Nonnull String teamId) {
    this.teamId = teamId;
    this.reaconPresentFields.add(SERIALIZED_NAME_TEAM_ID);
  }


  public SheetWorkflow updatedAt(@javax.annotation.Nonnull String updatedAt) {
    this.updatedAt = updatedAt;
    this.reaconPresentFields.add(SERIALIZED_NAME_UPDATED_AT);
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nonnull
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(@javax.annotation.Nonnull String updatedAt) {
    this.updatedAt = updatedAt;
    this.reaconPresentFields.add(SERIALIZED_NAME_UPDATED_AT);
  }


  public SheetWorkflow validation(@javax.annotation.Nonnull SheetWorkflowValidation validation) {
    this.validation = validation;
    this.reaconPresentFields.add(SERIALIZED_NAME_VALIDATION);
    return this;
  }

  /**
   * Get validation
   * @return validation
   */
  @javax.annotation.Nonnull
  public SheetWorkflowValidation getValidation() {
    return validation;
  }

  public void setValidation(@javax.annotation.Nonnull SheetWorkflowValidation validation) {
    this.validation = validation;
    this.reaconPresentFields.add(SERIALIZED_NAME_VALIDATION);
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the SheetWorkflow instance itself
   */
  public SheetWorkflow putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SheetWorkflow sheetWorkflow = (SheetWorkflow) o;
    return Objects.equals(this.capability, sheetWorkflow.capability) &&
        Objects.equals(this.config, sheetWorkflow.config) &&
        Objects.equals(this.connectionId, sheetWorkflow.connectionId) &&
        Objects.equals(this.createdAt, sheetWorkflow.createdAt) &&
        Objects.equals(this.id, sheetWorkflow.id) &&
        Objects.equals(this.label, sheetWorkflow.label) &&
        Objects.equals(this.revision, sheetWorkflow.revision) &&
        Objects.equals(this.state, sheetWorkflow.state) &&
        Objects.equals(this.teamId, sheetWorkflow.teamId) &&
        Objects.equals(this.updatedAt, sheetWorkflow.updatedAt) &&
        Objects.equals(this.validation, sheetWorkflow.validation)&&
        Objects.equals(this.additionalProperties, sheetWorkflow.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(capability, config, connectionId, createdAt, id, label, revision, state, teamId, updatedAt, validation, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SheetWorkflow {\n");
    sb.append("    capability: ").append(toIndentedString(capability)).append("\n");
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("    connectionId: ").append(toIndentedString(connectionId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    revision: ").append(toIndentedString(revision)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    teamId: ").append(toIndentedString(teamId)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    validation: ").append(toIndentedString(validation)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("capability", "config", "connectionId", "createdAt", "id", "label", "revision", "state", "teamId", "updatedAt", "validation"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("capability", "config", "connectionId", "createdAt", "id", "label", "revision", "state", "teamId", "updatedAt", "validation"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SheetWorkflow
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SheetWorkflow.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in SheetWorkflow is not found in the empty JSON string", SheetWorkflow.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SheetWorkflow.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("capability").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `capability` to be a primitive type in the JSON string but got `%s`", jsonObj.get("capability").toString()));
      }
      if (!jsonObj.get("connectionId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `connectionId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("connectionId").toString()));
      }
      if (!jsonObj.get("createdAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `createdAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("createdAt").toString()));
      }
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("label").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `label` to be a primitive type in the JSON string but got `%s`", jsonObj.get("label").toString()));
      }
      if (!jsonObj.get("state").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `state` to be a primitive type in the JSON string but got `%s`", jsonObj.get("state").toString()));
      }
      if (!jsonObj.get("teamId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `teamId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("teamId").toString()));
      }
      if (!jsonObj.get("updatedAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `updatedAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("updatedAt").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SheetWorkflow.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SheetWorkflow' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SheetWorkflow> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SheetWorkflow.class));

       return (TypeAdapter<T>) new TypeAdapter<SheetWorkflow>() {
           @Override
           public void write(JsonWriter out, SheetWorkflow value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             if (value.capability == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_CAPABILITY)) obj.add(SERIALIZED_NAME_CAPABILITY, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_CAPABILITY);
             }
             if (value.config == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_CONFIG)) obj.add(SERIALIZED_NAME_CONFIG, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_CONFIG);
             }
             if (value.connectionId == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_CONNECTION_ID)) obj.add(SERIALIZED_NAME_CONNECTION_ID, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_CONNECTION_ID);
             }
             if (value.createdAt == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_CREATED_AT)) obj.add(SERIALIZED_NAME_CREATED_AT, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_CREATED_AT);
             }
             if (value.id == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_ID)) obj.add(SERIALIZED_NAME_ID, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_ID);
             }
             if (value.label == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_LABEL)) obj.add(SERIALIZED_NAME_LABEL, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_LABEL);
             }
             if (value.revision == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_REVISION)) obj.add(SERIALIZED_NAME_REVISION, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_REVISION);
             }
             if (value.state == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_STATE)) obj.add(SERIALIZED_NAME_STATE, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_STATE);
             }
             if (value.teamId == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_TEAM_ID)) obj.add(SERIALIZED_NAME_TEAM_ID, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_TEAM_ID);
             }
             if (value.updatedAt == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_UPDATED_AT)) obj.add(SERIALIZED_NAME_UPDATED_AT, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_UPDATED_AT);
             }
             if (value.validation == null) {
               if (value.reaconPresentFields.contains(SERIALIZED_NAME_VALIDATION)) obj.add(SERIALIZED_NAME_VALIDATION, com.google.gson.JsonNull.INSTANCE);
               else obj.remove(SERIALIZED_NAME_VALIDATION);
             }
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonNull()) {
                     obj.add(entry.getKey(), JsonNull.INSTANCE);
                   } else if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             boolean previousSerializeNulls = out.getSerializeNulls();
             out.setSerializeNulls(true);
             try { elementAdapter.write(out, obj); }
             finally { out.setSerializeNulls(previousSerializeNulls); }
           }

           @Override
           public SheetWorkflow read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             SheetWorkflow instance = thisAdapter.fromJsonTree(jsonObj);
             instance.reaconPresentFields.addAll(jsonObj.keySet());
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SheetWorkflow given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SheetWorkflow
   * @throws IOException if the JSON string is invalid with respect to SheetWorkflow
   */
  public static SheetWorkflow fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SheetWorkflow.class);
  }

  /**
   * Convert an instance of SheetWorkflow to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

